/* BOSS */
function initBoss(){setHUD("CUORE DI MUSINO","✨ 0 / 3");setLives(3);joy.classList.add("on");action.classList.add("on");action.classList.remove("ready");action.textContent="0 / 3";tip.textContent="Raccogli 3 ✨ dorate. Quando il tasto si illumina, premi COLPISCI.";state={p:{x:W/2,y:H*.68,r:18},boss:{x:W/2,y:150,r:42,hp:3},phase:1,lives:3,shots:[],orbs:[],spawn:.72,orbSpawn:.58,energy:0,inv:0,beam:0,grace:1.0};setCanvasTap(()=>{});action.onclick=()=>bossHit()}
function bossHit(){if(!active||level!==6||state.energy<3)return;state.energy=0;metric.textContent="✨ 0 / 3";action.textContent="0 / 3";action.classList.remove("ready");state.boss.hp--;state.beam=.30;tip.textContent="Preso ❤️ Ora raccogli altre 3 ✨.";if(state.boss.hp<=0){if(state.phase<3){state.phase++;state.boss.hp=3;state.shots=[];state.orbs=[];state.energy=0;state.grace=1.35;state.spawn=1.2;state.orbSpawn=.45;metric.textContent="✨ 0 / 3";action.textContent="0 / 3";action.classList.remove("ready");tip.textContent=state.phase===2?"Fase 2. Un attimo di pausa, poi si riparte.":"Ultima fase. Stessa cosa: 3 ✨ e poi COLPISCI."}else{active=false;setTimeout(()=>win("Hai vinto. Il cuore però si rifiuta di collaborare col concetto di sconfitta."),430)}}}
function bossCfg(){if(state.phase===1)return{interval:.64,speed:145,spread:.42,double:0};if(state.phase===2)return{interval:.66,speed:150,spread:.46,double:.06};return{interval:.52,speed:172,spread:.50,double:.16}}
function spawnBossShot(){const c=bossCfg(),a=Math.atan2(state.p.y-state.boss.y,state.p.x-state.boss.x)+(Math.random()-.5)*c.spread,sp=c.speed;state.shots.push({x:state.boss.x,y:state.boss.y+32,vx:Math.cos(a)*sp,vy:Math.sin(a)*sp,r:11});if(Math.random()<c.double)state.shots.push({x:state.boss.x,y:state.boss.y+32,vx:Math.cos(a+.34)*sp*.92,vy:Math.sin(a+.34)*sp*.92,r:10})}
function spawnOrb(){state.orbs.push({x:44+Math.random()*(W-88),y:245+Math.random()*(H-470),r:13,life:5.5})}
function updateBoss(dt){let p=state.p,sp=232;p.x=Math.max(20,Math.min(W-20,p.x+j.dx*sp*dt));p.y=Math.max(230,Math.min(H-155,p.y+j.dy*sp*dt));state.inv=Math.max(0,state.inv-dt);state.beam=Math.max(0,state.beam-dt);state.grace=Math.max(0,state.grace-dt);if(state.grace<=0){state.spawn-=dt;if(state.spawn<=0){const c=bossCfg();state.spawn=c.interval;spawnBossShot()}}state.orbSpawn-=dt;if(state.orbSpawn<=0){state.orbSpawn=.82;spawnOrb()}for(let i=state.shots.length-1;i>=0;i--){let s=state.shots[i];s.x+=s.vx*dt;s.y+=s.vy*dt;if(s.y>H+35||s.x<-35||s.x>W+35){state.shots.splice(i,1);continue}if(state.inv<=0&&Math.hypot(s.x-p.x,s.y-p.y)<s.r+p.r-4){state.shots.splice(i,1);state.lives--;setLives(state.lives);state.inv=.85;flashBad();if(state.lives<=0)return lose("Il cuore ha vinto questo giro. Rifacciamolo.")}}for(let i=state.orbs.length-1;i>=0;i--){let o=state.orbs[i];o.life-=dt;if(o.life<=0){state.orbs.splice(i,1);continue}if(Math.hypot(o.x-p.x,o.y-p.y)<o.r+p.r){state.orbs.splice(i,1);state.energy=Math.min(3,state.energy+1);metric.textContent="✨ "+state.energy+" / 3";action.textContent=state.energy>=3?"COLPISCI":state.energy+" / 3";if(state.energy>=3){action.classList.add("ready");tip.textContent="Carico! Ora premi COLPISCI a sinistra 💥"}else tip.textContent="Brava: "+state.energy+"/3 ✨. Prendine ancora "+(3-state.energy)+"."}}state.shots.forEach(s=>{circle(s.x,s.y,23,"#ff4f7810");emoji("💋",s.x,s.y,30)});state.orbs.forEach(o=>{circle(o.x,o.y,o.r+10,"#ffd58e20");emoji("✨",o.x,o.y,31)});let b=state.boss;circle(b.x,b.y,b.r+22,"#ff4f7814");emoji("❤️",b.x,b.y,82);txt("MUSINO",b.x,b.y+66,10,"#a99ba8");txt("FASE "+state.phase+" / 3",b.x,b.y+86,11,"#d8cbd3");for(let i=0;i<3;i++){rr(W/2-54+i*38,218,30,5,3);ctx.fillStyle=i<b.hp?"#ff78a7":"#ffffff10";ctx.fill()}if(state.beam>0){ctx.strokeStyle="#ffb1ca";ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(p.x,p.y-10);ctx.lineTo(b.x,b.y+25);ctx.stroke()}avatar(p.x,p.y,p.r,state.inv);if(state.grace>0)txt("pronta?",W/2,270,13,"#d7cad2")}
document.addEventListener("visibilitychange",()=>{if(document.hidden&&active){active=false;cancelAnimationFrame(raf);$("#resultStatus").textContent="PAUSA";$("#resultTitle").textContent="Hai chiuso il gioco.";$("#resultText").textContent="Nessun problema, riparti da qui.";$("#resultBtn").textContent="riprendi";$("#resultBtn").onclick=()=>{overlay.classList.remove("on");startLevel(level)};overlay.classList.add("on")}});
renderMap();
