/* BOSS */
function initBoss(){setHUD("BOSS // CUORE DI MUSINO","FASE 1 / 3");setLives(3);joy.classList.add("on");action.classList.add("on");action.classList.remove("ready");action.textContent="0/3";tip.textContent="Raccogli 3 ✦ dorate. Poi premi COLPISCI a sinistra.";state={p:{x:W/2,y:H*.76,r:14},boss:{x:W/2,y:130,r:42,hp:3},phase:1,lives:3,shots:[],orbs:[],spawn:.7,orbSpawn:.75,energy:0,inv:0,beam:0,grace:.8};setCanvasTap(()=>{});action.onclick=()=>bossHit()}
function bossHit(){if(!active||level!==6||state.energy<3)return;state.energy=0;action.textContent="0/3";action.classList.remove("ready");state.boss.hp--;state.beam=.32;tip.textContent="Bel colpo. Ora raccogli altre 3 ✦.";if(state.boss.hp<=0){if(state.phase<3){state.phase++;state.boss.hp=3;metric.textContent="FASE "+state.phase+" / 3";state.shots=[];state.orbs=[];state.energy=0;state.grace=1.1;state.spawn=1.1;state.orbSpawn=.55;action.textContent="0/3";action.classList.remove("ready");tip.textContent=state.phase===2?"Fase 2. Respira: hai un attimo di tregua.":"Ultima fase. Sempre 3 ✦, poi COLPISCI."}else{active=false;setTimeout(()=>win("Hai portato il cuore a zero. Il sistema però non sembra d'accordo."),450)}}}
function bossCfg(){if(state.phase===1)return{interval:.62,speed:148,spread:.40,double:0};if(state.phase===2)return{interval:.56,speed:160,spread:.42,double:.16};return{interval:.44,speed:188,spread:.50,double:.32}}
function spawnBossShot(){const c=bossCfg(),a=Math.atan2(state.p.y-state.boss.y,state.p.x-state.boss.x)+(Math.random()-.5)*c.spread,sp=c.speed;state.shots.push({x:state.boss.x,y:state.boss.y+25,vx:Math.cos(a)*sp,vy:Math.sin(a)*sp,r:8+state.phase*.7});if(Math.random()<c.double)state.shots.push({x:state.boss.x,y:state.boss.y+25,vx:Math.cos(a+.34)*sp*.95,vy:Math.sin(a+.34)*sp*.95,r:7.5})}
function spawnOrb(){state.orbs.push({x:40+Math.random()*(W-80),y:210+Math.random()*(H-380),r:12,life:5.2})}
function updateBoss(dt){let p=state.p,sp=230;p.x=Math.max(18,Math.min(W-18,p.x+j.dx*sp*dt));p.y=Math.max(200,Math.min(H-22,p.y+j.dy*sp*dt));state.inv=Math.max(0,state.inv-dt);state.beam=Math.max(0,state.beam-dt);state.grace=Math.max(0,state.grace-dt);if(state.grace<=0){state.spawn-=dt;if(state.spawn<=0){const c=bossCfg();state.spawn=c.interval;spawnBossShot()}}state.orbSpawn-=dt;if(state.orbSpawn<=0){state.orbSpawn=1.0;spawnOrb()}for(let i=state.shots.length-1;i>=0;i--){let s=state.shots[i];s.x+=s.vx*dt;s.y+=s.vy*dt;if(s.y>H+25||s.x<-25||s.x>W+25){state.shots.splice(i,1);continue}if(state.inv<=0&&Math.hypot(s.x-p.x,s.y-p.y)<s.r+p.r){state.shots.splice(i,1);state.lives--;setLives(state.lives);state.inv=.82;flashBad();if(state.lives<=0)return lose("Boss perso. Il cuore di Musino resta fastidiosamente resistente.")}}for(let i=state.orbs.length-1;i>=0;i--){let o=state.orbs[i];o.life-=dt;if(o.life<=0){state.orbs.splice(i,1);continue}if(Math.hypot(o.x-p.x,o.y-p.y)<o.r+p.r){state.orbs.splice(i,1);state.energy=Math.min(3,state.energy+1);action.textContent=state.energy>=3?"COLPISCI":state.energy+"/3";if(state.energy>=3){action.classList.add("ready");tip.textContent="CARICO! Premi COLPISCI a sinistra."}else{tip.textContent="Energia: "+state.energy+"/3. Prendi ancora "+(3-state.energy)+" ✦."}}}state.shots.forEach(s=>{circle(s.x,s.y,s.r+4,"#ff4f7820");heart(s.x,s.y,s.r,"#ff557e")});state.orbs.forEach(o=>{circle(o.x,o.y,o.r+8,"#ffd58e20");circle(o.x,o.y,o.r,"#ffd58e");txt("✦",o.x,o.y+1,15,"#3b2b16")});let b=state.boss;circle(b.x,b.y,b.r+18,"#ff4f7812");emoji("❤️",b.x,b.y,78);txt("MUSINO",b.x,b.y+62,10,"#a99ba8");for(let i=0;i<3;i++){rr(W/2-54+i*38,194,30,5,3);ctx.fillStyle=i<b.hp?"#ff78a7":"#ffffff10";ctx.fill()}if(state.beam>0){ctx.strokeStyle="#ffb1ca";ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(p.x,p.y-10);ctx.lineTo(b.x,b.y+18);ctx.stroke()}circle(p.x,p.y,p.r+5,state.inv>0?"#ffffff22":"#ffb1ca20");circle(p.x,p.y,p.r,"#f3e8ef");txt("A",p.x,p.y,11,"#351824");if(state.grace>0)txt("preparati…",W/2,245,13,"#d7cad2")}
document.addEventListener("visibilitychange",()=>{if(document.hidden&&active){active=false;cancelAnimationFrame(raf);$("#resultStatus").textContent="PAUSA";$("#resultTitle").textContent="Sei uscita dal gioco.";$("#resultText").textContent="Nessuna penalità. Questa volta.";$("#resultBtn").textContent="riprendi";$("#resultBtn").onclick=()=>{overlay.classList.remove("on");startLevel(level)};overlay.classList.add("on")}});
renderMap();
