"use strict";
const $=s=>document.querySelector(s),canvas=$("#gameCanvas"),ctx=canvas.getContext("2d"),home=$("#home"),intro=$("#introLevel"),game=$("#game"),hud=$("#hud"),overlay=$("#resultOverlay"),final=$("#final"),metric=$("#metric"),livesEl=$("#lives"),stageTitle=$("#stageTitle"),tip=$("#tip"),gestureHint=$("#gestureHint");
let W=0,H=0,DPR=1,raf=0,active=false,level=1,state=null,last=0;
let unlocked=Math.max(1,Math.min(6,+localStorage.getItem("amelieV3Unlocked")||1));
const taunts=["Quasi. Molto quasi.","Okay, questa la cancelliamo dagli archivi.","Amelie… ci siamo quasi.","Musino non giudica. Quasi mai.","Rifalla: era prendibile.","Questa era chiaramente di prova.","Un'altra e passa tutto."];
const info={
1:{title:"Rose Rush",desc:"Tre corsie, velocità crescente. Scorri a destra e sinistra, prendi rose e bacini, evita i cuori rotti.",difficulty:"●●○",rules:[["↔️","scorri per cambiare corsia"],["🌹","rose = 1 punto, bacini = 2"],["18","raggiungi 18 punti"]]},
2:{title:"Kiss Pong",desc:"Un bacino, una racchetta e dodici cuori da rompere. Tieni il dito e sposta la racchetta. Sì, è praticamente sport.",difficulty:"●●○",rules:[["👆","trascina la racchetta"],["💋","non far cadere il bacino"],["12","rompi tutti i cuori"]]},
3:{title:"Costellazione",desc:"Collega i cuori nell'ordine giusto tenendo il dito sullo schermo. Toccare un cuore rotto costa una vita.",difficulty:"●●●",rules:[["✦","segui i numeri"],["🫶","tieni il dito e trascina"],["💔","evita gli ostacoli mobili"]]},
4:{title:"Il nostro ritmo",desc:"Le note scendono su quattro corsie. Tocca la corsia giusta quando arrivano sulla linea rosa.",difficulty:"●●●",rules:[["🎵","4 corsie"],["✨","più precisione = più combo"],["75%","serve almeno questa precisione"]]},
5:{title:"La cassaforte",desc:"Tre dischi concentrici, tre combinazioni. Trascina ogni anello fino al simbolo corretto e tienilo fermo per sbloccarlo.",difficulty:"●●●",rules:[["⭕","trascina gli anelli"],["🔐","3 combinazioni"],["❤️","3 errori massimi"]]},
6:{title:"Sincronizzazione finale",desc:"Non devi battere nessuno. Devi far combaciare due segnali che continuano a scappare: tre fasi, una sola barra di stabilità.",difficulty:"●●●",rules:[["🫶","trascina il cursore"],["💗","resta dentro la zona luminosa"],["3×","completa tre fasi"]]}
};
const playerImg=new Image();playerImg.src="profile.svg?v=10";
function resize(){DPR=Math.min(2,devicePixelRatio||1);W=innerWidth;H=innerHeight;canvas.width=W*DPR;canvas.height=H*DPR;canvas.style.width=W+"px";canvas.style.height=H+"px";ctx.setTransform(DPR,0,0,DPR,0,0)}addEventListener("resize",resize);resize();
function screensOff(){document.querySelectorAll(".screen").forEach(s=>s.classList.remove("on"))}
function showHome(){stop();screensOff();home.classList.add("on");renderMap()}
function renderMap(){const m=$("#homeMap");m.innerHTML="";for(let i=1;i<=6;i++){const p=document.createElement("div");p.className="pip"+(i<unlocked?" done":i===unlocked?" now":"");m.appendChild(p)}$("#startBtn").textContent=unlocked>1?"continua":"inizia"}
function introLevel(n){stop();level=n;screensOff();intro.classList.add("on");$("#bigNum").textContent=n===6?"FIN":String(n).padStart(2,"0");$("#introBrand").textContent=n===6?"FINALE":"LIVELLO "+String(n).padStart(2,"0");$("#difficulty").textContent=info[n].difficulty;$("#introTitle").textContent=info[n].title;$("#introDesc").textContent=info[n].desc;const r=$("#introRules");r.innerHTML="";info[n].rules.forEach(([a,b])=>{const el=document.createElement("div");el.className="rule";el.innerHTML=`<div class="ruleIcon">${a}</div><div class="ruleText"><b>${b}</b><span>${subRule(b)}</span></div>`;r.appendChild(el)})}
function subRule(b){if(b.includes("vite")||b.includes("errori"))return"Se finiscono, riparti solo da qui.";if(b.includes("corsia"))return"Un tap vale solo al momento giusto.";if(b.includes("trascina"))return"Pensato per il pollice.";if(b.includes("punti"))return"La combo accelera il punteggio.";if(b.includes("fasi"))return"Ogni fase cambia comportamento.";return"Regola semplice."}
$("#startBtn").onclick=()=>introLevel(unlocked);$("#resetBtn").onclick=()=>{localStorage.removeItem("amelieV3Unlocked");unlocked=1;renderMap()};$("#playBtn").onclick=()=>startLevel(level);
function startLevel(n){screensOff();overlay.classList.remove("on");game.classList.add("on");level=n;active=true;last=performance.now();hud.classList.add("on");gestureHint.textContent="";if(n===1)initRunner();if(n===2)initPong();if(n===3)initConstellation();if(n===4)initRhythm();if(n===5)initVault();if(n===6)initSyncBoss();cancelAnimationFrame(raf);raf=requestAnimationFrame(loop)}
function setHUD(t,m=""){stageTitle.textContent=t;metric.textContent=m}function setLives(n){livesEl.textContent="♥".repeat(Math.max(0,n))+"♡".repeat(Math.max(0,3-n))}
function stop(){active=false;cancelAnimationFrame(raf);game.classList.remove("on");hud.classList.remove("on");tip.textContent="";gestureHint.textContent="";clearInput()}
function win(text=""){active=false;cancelAnimationFrame(raf);if(level<6&&unlocked<level+1){unlocked=level+1;localStorage.setItem("amelieV3Unlocked",unlocked)}$("#resultStatus").textContent=level===6?"FINITO":"LIVELLO SUPERATO";$("#resultTitle").textContent=level===6?"Ce l'hai fatta ❤️":"Brava, Amelie.";$("#resultText").textContent=text;$("#resultBtn").textContent=level===6?"vedi il finale":"continua";$("#resultBtn").onclick=()=>{overlay.classList.remove("on");level===6?showFinal():introLevel(level+1)};overlay.classList.add("on");sfx("win")}
function lose(reason){active=false;cancelAnimationFrame(raf);$("#resultStatus").textContent="RIPROVA";$("#resultTitle").textContent=taunts[Math.floor(Math.random()*taunts.length)];$("#resultText").textContent=reason;$("#resultBtn").textContent="riprova";$("#resultBtn").onclick=()=>{overlay.classList.remove("on");startLevel(level)};overlay.classList.add("on");sfx("bad")}
function showFinal(){stop();screensOff();final.classList.add("on");localStorage.setItem("amelieV3Unlocked",6)}
function loop(t){if(!active)return;const dt=Math.min(.034,(t-last)/1000);last=t;ctx.clearRect(0,0,W,H);drawBackdrop();if(level===1)updateRunner(dt);else if(level===2)updatePong(dt);else if(level===3)updateConstellation(dt);else if(level===4)updateRhythm(dt);else if(level===5)updateVault(dt);else updateSyncBoss(dt);raf=requestAnimationFrame(loop)}
function drawBackdrop(){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,"#110b14");g.addColorStop(1,"#09070c");ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle="#ff78a709";for(let i=0;i<7;i++){ctx.beginPath();ctx.arc((i*89+performance.now()*.008)%W,(i*137)%H,40+i*5,0,Math.PI*2);ctx.fill()}}
function rr(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}function circle(x,y,r,c){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=c;ctx.fill()}function txt(s,x,y,size=16,color="#fff",align="center",weight=800){ctx.fillStyle=color;ctx.font=`${weight} ${size}px -apple-system,system-ui,sans-serif`;ctx.textAlign=align;ctx.textBaseline="middle";ctx.fillText(s,x,y)}function emoji(s,x,y,size=36){ctx.save();ctx.font=`${size}px "Apple Color Emoji","Segoe UI Emoji",sans-serif`;ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(s,x,y);ctx.restore()}
function avatar(x,y,r){ctx.save();ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.clip();if(playerImg.complete&&playerImg.naturalWidth)ctx.drawImage(playerImg,x-r,y-r,r*2,r*2);else{ctx.fillStyle="#ffdbe7";ctx.fillRect(x-r,y-r,r*2,r*2)}ctx.restore();ctx.beginPath();ctx.arc(x,y,r+2,0,Math.PI*2);ctx.strokeStyle="#ffb7cf";ctx.lineWidth=3;ctx.stroke()}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}function flashBad(){game.classList.remove("shake");void game.offsetWidth;game.classList.add("shake")}
let inputHandlers=[];function on(el,type,fn,opt){el.addEventListener(type,fn,opt);inputHandlers.push(()=>el.removeEventListener(type,fn,opt))}function clearInput(){inputHandlers.forEach(f=>f());inputHandlers=[]}
function pos(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
function sfx(type){try{const A=window.AudioContext||window.webkitAudioContext;if(!A)return;window._ac=window._ac||new A();const ac=window._ac,o=ac.createOscillator(),g=ac.createGain();o.connect(g);g.connect(ac.destination);let f=type==="win"?620:type==="bad"?140:380;o.frequency.setValueAtTime(f,ac.currentTime);if(type==="win")o.frequency.exponentialRampToValueAtTime(900,ac.currentTime+.13);g.gain.setValueAtTime(.035,ac.currentTime);g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+.16);o.start();o.stop(ac.currentTime+.17)}catch(e){}}
renderMap();
