"use strict";
const $=s=>document.querySelector(s), canvas=$("#gameCanvas"), ctx=canvas.getContext("2d");
const home=$("#home"), intro=$("#introLevel"), game=$("#game"), hud=$("#hud"), overlay=$("#resultOverlay"), final=$("#final");
const metric=$("#metric"), livesEl=$("#lives"), stageTitle=$("#stageTitle"), tip=$("#tip"), joy=$("#joy"), stick=$("#stick"), action=$("#action");
const playerImg=new Image(); playerImg.src="profile.svg?v=4";
let W=0,H=0,DPR=1, raf=0, active=false, level=1, state=null, last=0;
let unlocked=Math.max(1,Math.min(6,+localStorage.getItem("amelieUnlocked")||1));
const taunts=["Questa era di riscaldamento.","Okay, ritentiamo.","Amelie… quasi.","Musino ha visto tutto, ma giudica poco.","Un altro tentativo e ci siamo.","Va bene, questa gliela concediamo.","Riprova, che eri vicina.","Il gioco per un attimo si è sentito forte."];
const info={
1:{title:"Caccia ai bacini",desc:"Prendi 💋 e 🌹, lascia stare i 💔 e fai abbastanza punti prima che finisca il tempo.",rules:[["❤️","3 vite"],["14","punti per vincere"],["💔","quello meglio non toccarlo"]]},
2:{title:"Schiva i bacini",desc:"Muoviti col joystick a destra e resisti 18 secondi ai 💋 che arrivano dai bordi.",rules:[["🕹️","joystick a destra"],["18s","resisti fino alla fine"],["❤️","3 colpi e riprovi"]]},
3:{title:"Tempismo",desc:"Tocca lo schermo quando l'indicatore passa nella zona rosa. Cinque centri e hai finito.",rules:[["👆","tocca lo schermo"],["5×","cinque centri"],["❤️","tre errori massimi"]]},
4:{title:"Memoria",desc:"Guarda i simboli accendersi e ripeti la sequenza. Se lo stesso simbolo compare due volte, lo vedrai lampeggiare due volte.",rules:[["✨","guarda bene"],["7","sette round"],["❤️","3 errori totali"]]},
5:{title:"Labirinto del cuore",desc:"Porta ❤️ fino all'uscita. Niente timer: prenditi il tempo che serve e cerca il passaggio giusto.",rules:[["🕹️","joystick a destra"],["♾️","nessun limite di tempo"],["❤️","3 collisioni"]]},
6:{title:"Cuore di Musino",desc:"Schiva i 💋, raccogli 3 ✨ dorate e solo allora premi COLPISCI. Joystick a destra, tasto a sinistra.",rules:[["✨","raccogline 3"],["💥","poi premi COLPISCI"],["❤️","3 vite per il boss"]]}
};
function resize(){DPR=Math.min(2,devicePixelRatio||1);W=innerWidth;H=innerHeight;canvas.width=Math.floor(W*DPR);canvas.height=Math.floor(H*DPR);canvas.style.width=W+"px";canvas.style.height=H+"px";ctx.setTransform(DPR,0,0,DPR,0,0)}
addEventListener("resize",resize);resize();
function screensOff(){document.querySelectorAll(".screen").forEach(x=>x.classList.remove("on"))}
function showHome(){stop();screensOff();home.classList.add("on");renderMap()}
function renderMap(){const m=$("#homeMap");m.innerHTML="";for(let i=1;i<=6;i++){let p=document.createElement("div");p.className="pip"+(i<unlocked?" done":i===unlocked?" now":"");m.appendChild(p)}$("#startBtn").textContent=unlocked>1?"continua":"inizia"}
function introLevel(n){stop();level=n;screensOff();intro.classList.add("on");$("#bigNum").textContent=n===6?"BOSS":String(n).padStart(2,"0");$("#introBrand").textContent=n===6?"SFIDA FINALE":"LIVELLO "+String(n).padStart(2,"0");$("#introTitle").textContent=info[n].title;$("#introDesc").textContent=info[n].desc;const r=$("#introRules");r.innerHTML="";info[n].rules.forEach(([a,b])=>{let d=document.createElement("div");d.className="rule";let cls="icon"+(String(a).length>3?" long":"");d.innerHTML='<div class="'+cls+'">'+a+'</div><div><b>'+b+'</b><br><span>'+ruleSub(a,b)+'</span></div>';r.appendChild(d)})}
function ruleSub(a,b){if(b.includes("vite")||b.includes("errori")||b.includes("collisioni")||b.includes("colpi"))return "Se finiscono, riparti da questo livello.";if(b.includes("joystick"))return "Pensato per il pollice destro.";if(b.includes("nessun limite"))return "Qui puoi andare con calma.";if(b.includes("tempo"))return "Vai tranquilla, ma non troppo.";if(b.includes("round"))return "Ogni giro aggiunge qualcosa.";if(b.includes("raccogline"))return "Servono per caricare il colpo.";if(b.includes("COLPISCI"))return "Si illumina quando è pronto.";return "Regola semplice."}
$("#startBtn").onclick=()=>introLevel(unlocked);$("#resetBtn").onclick=()=>{localStorage.removeItem("amelieUnlocked");localStorage.removeItem("amelieBest");unlocked=1;renderMap()};$("#playBtn").onclick=()=>startLevel(level);
function setHUD(title,m=""){stageTitle.textContent=title;metric.textContent=m;hud.classList.add("on")}
function setLives(n){livesEl.textContent="♥".repeat(Math.max(0,n))+"♡".repeat(Math.max(0,3-n))}
function startLevel(n){screensOff();overlay.classList.remove("on");game.classList.add("on");level=n;active=true;last=performance.now();action.classList.remove("on","ready");joy.classList.remove("on");tip.textContent="";resetJoy();if(n===1)initCatch();if(n===2)initDodge();if(n===3)initTiming();if(n===4)initMemory();if(n===5)initMaze();if(n===6)initBoss();cancelAnimationFrame(raf);raf=requestAnimationFrame(loop)}
function stop(){active=false;cancelAnimationFrame(raf);game.classList.remove("on");hud.classList.remove("on");joy.classList.remove("on");action.classList.remove("on","ready");resetJoy()}
function win(extra=""){active=false;cancelAnimationFrame(raf);const next=Math.min(7,level+1);if(level<6&&unlocked<next){unlocked=next;localStorage.setItem("amelieUnlocked",unlocked)}$("#resultStatus").textContent="LIVELLO SUPERATO";$("#resultTitle").textContent=level===6?"Ce l'hai fatta ❤️":"Brava, Amelie.";$("#resultText").textContent=extra||["Bacini raccolti. Tutto regolare.","Sei sopravvissuta ai bacini. Per ora.","Bel tempismo.","Memoria promossa.","Cuore arrivato a destinazione."][level-1];$("#resultBtn").textContent=level===6?"vedi il finale":"continua";$("#resultBtn").onclick=()=>{overlay.classList.remove("on");if(level===6)showFinal();else introLevel(level+1)};overlay.classList.add("on")}
function lose(reason=""){active=false;cancelAnimationFrame(raf);$("#resultStatus").textContent="RIPROVA";$("#resultTitle").textContent=taunts[Math.floor(Math.random()*taunts.length)];$("#resultText").textContent=reason||"Facciamone un'altra.";$("#resultBtn").textContent="riprova";$("#resultBtn").onclick=()=>{overlay.classList.remove("on");startLevel(level)};overlay.classList.add("on")}
function showFinal(){stop();screensOff();final.classList.add("on");localStorage.setItem("amelieUnlocked",6)}
function loop(t){if(!active)return;const dt=Math.min(.034,(t-last)/1000);last=t;ctx.clearRect(0,0,W,H);if(level===1)updateCatch(dt,t);else if(level===2)updateDodge(dt,t);else if(level===3)updateTiming(dt,t);else if(level===4)updateMemory(dt,t);else if(level===5)updateMaze(dt,t);else updateBoss(dt,t);raf=requestAnimationFrame(loop)}
function rr(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function txt(s,x,y,size=16,color="#fff",align="center",weight=800){ctx.fillStyle=color;ctx.font=weight+" "+size+"px -apple-system,system-ui,sans-serif";ctx.textAlign=align;ctx.textBaseline="middle";ctx.fillText(s,x,y)}
function emoji(s,x,y,size=42){ctx.save();ctx.font=size+'px "Apple Color Emoji","Segoe UI Emoji",sans-serif';ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(s,x,y);ctx.restore()}
function circle(x,y,r,c){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=c;ctx.fill()}
function avatar(x,y,r,inv=0){ctx.save();ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.clip();if(playerImg.complete&&playerImg.naturalWidth)ctx.drawImage(playerImg,x-r,y-r,r*2,r*2);else{ctx.fillStyle="#f4d9e5";ctx.fillRect(x-r,y-r,r*2,r*2)}ctx.restore();ctx.beginPath();ctx.arc(x,y,r+2,0,Math.PI*2);ctx.strokeStyle=inv>0?"#ffffffaa":"#ffb1ca";ctx.lineWidth=3;ctx.stroke()}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function pointerPos(e){const r=canvas.getBoundingClientRect(),p=e.touches?e.touches[0]:e;return{x:p.clientX-r.left,y:p.clientY-r.top}}
let canvasHandler=null;function setCanvasTap(fn){if(canvasHandler)canvas.removeEventListener("pointerdown",canvasHandler);canvasHandler=e=>{e.preventDefault();fn(pointerPos(e),e)};canvas.addEventListener("pointerdown",canvasHandler,{passive:false})}
