"use strict";
const $=s=>document.querySelector(s), screens=[...document.querySelectorAll('.screen')], game=$('#game'), stage=$('#gameStage'), metric=$('#metric');
let hint=$('#hint'), level=1, unlocked=Math.max(1,Math.min(6,+localStorage.getItem('amelieV16Unlocked')||1)), cleanups=[], timers=[];
const defs=[
 {title:'Continua',desc:'Premi il pulsante per completare il livello.'},
 {title:'Stabilità',desc:'Trascina 😇 dentro la zona verde e mantienila lì per 6 secondi totali.'},
 {title:'Direzioni',desc:'Esegui 10 swipe nella direzione indicata.'},
 {title:'Labirinto',desc:'Usa le frecce per portare 🐸 fino a 🚪.'},
 {title:'Precisione',desc:'Tocca il bersaglio 12 volte.'}
];
function show(id){screens.forEach(s=>s.classList.remove('on'));game.classList.remove('on');$('#'+id).classList.add('on')}
function renderProgress(){let p=$('#progress');p.innerHTML='';for(let i=1;i<=5;i++){let d=document.createElement('div');d.className='step'+(i<unlocked?' done':i===unlocked?' now':'');d.textContent=String(i).padStart(2,'0');p.appendChild(d)}$('#startBtn').textContent=unlocked>1&&unlocked<=5?'CONTINUA':'INIZIA'}
function intro(n){level=n;show('intro');$('#introNo').textContent='LIVELLO '+String(n).padStart(2,'0');$('#introTitle').textContent=defs[n-1].title;$('#introDesc').textContent=defs[n-1].desc}
function clean(){cleanups.forEach(f=>{try{f()}catch{}});cleanups=[];timers.forEach(clearTimeout);timers=[];stage.innerHTML='<div class="hint" id="hint"></div>';hint=$('#hint')}
function later(fn,ms){let id=setTimeout(fn,ms);timers.push(id);return id}
function on(el,ev,fn,opt){el.addEventListener(ev,fn,opt);cleanups.push(()=>el.removeEventListener(ev,fn,opt))}
function fx(text,bad=true){let f=$('#errorFlash'),t=$('#errorText');f.style.background=bad?'#ff5a63':'#3568ff';f.classList.remove('go');t.classList.remove('go');void f.offsetWidth;f.classList.add('go');t.textContent=text;t.classList.add('go');stage.classList.remove('shake');void stage.offsetWidth;stage.classList.add('shake');navigator.vibrate?.(bad?[45,25,60]:[25])}
function start(){clean();screens.forEach(s=>s.classList.remove('on'));game.classList.add('on');$('#stageLabel').textContent='LIVELLO '+String(level).padStart(2,'0');[l1,l2,l3,l4,l5][level-1]()}
function win(text){unlocked=Math.max(unlocked,level<5?level+1:6);localStorage.setItem('amelieV16Unlocked',unlocked);$('#resultTitle').textContent='Completato';$('#resultText').textContent=text;$('#resultBtn').textContent=level===5?'VEDI RISULTATO':'CONTINUA';$('#resultBtn').onclick=()=>{$('#result').classList.remove('on');clean();level===5?fakeWin():intro(level+1)};$('#result').classList.add('on')}
$('#startBtn').onclick=()=>intro(Math.min(unlocked,5));$('#resetBtn').onclick=()=>{localStorage.removeItem('amelieV16Unlocked');unlocked=1;renderProgress()};$('#playBtn').onclick=start;

function l1(){hint.textContent='Premi CONTINUA.';metric.textContent='0 / 10';let area=document.createElement('div');area.className='escapeArea';let b=document.createElement('button');b.className='escapeBtn';b.textContent='CONTINUA';let stat=document.createElement('div');stat.className='attempt';stat.textContent='tentativi: 0';area.append(b,stat);stage.appendChild(area);let n=0,final=false,extra=false,decoy=null;function place(el=b){requestAnimationFrame(()=>{let w=area.clientWidth,h=area.clientHeight,bw=Math.max(142,el.offsetWidth||142),bh=Math.max(54,el.offsetHeight||54);el.style.transform='none';el.style.left=(12+Math.random()*Math.max(8,w-bw-24))+'px';el.style.top=(16+Math.random()*Math.max(8,h-bh-48))+'px'})}b.style.left='50%';b.style.top='44%';b.style.transform='translate(-50%,-50%)';function addDecoy(){if(decoy)return;decoy=document.createElement('button');decoy.className='escapeBtn fake';decoy.textContent='CONTINUA';area.appendChild(decoy);place(decoy);on(decoy,'pointerdown',e=>{e.preventDefault();fx('MANCATO');place(decoy)})}on(b,'pointerdown',e=>{e.preventDefault();if(final){if(!extra){extra=true;fx('RICALIBRAZIONE');b.textContent='CONTINUA';place();return}return win('Livello completato.')}n++;metric.textContent=n+' / 10';stat.textContent='tentativi: '+n;fx(['MANCATO','RIPROVA','QUASI','MANCATO','RIPROVA','QUASI','MANCATO','RIPROVA','QUASI','OK'][Math.min(n-1,9)]);if(n===5)addDecoy();if(n>=10){final=true;decoy?.remove();b.textContent='CONTINUA';b.style.left='50%';b.style.top='50%';b.style.transform='translate(-50%,-50%)';b.style.background='var(--green)';b.style.color='#12351d'}else{place();if(n>=7)later(()=>place(),145)}})}

function l2(){hint.textContent='Il centro di 😇 deve restare dentro il rettangolo verde.';metric.textContent='0.0 / 6.0s';let w=document.createElement('div');w.className='stabilizer';w.innerHTML='<div class="stabArena"><div class="safeZone"></div><div class="sliderLine"></div><button class="puck" aria-label="faccina"><span>😇</span></button></div><div class="stabBar"><i></i></div><div class="stabText">trascina la faccina orizzontalmente</div>';stage.appendChild(w);let arena=w.querySelector('.stabArena'),zone=w.querySelector('.safeZone'),puck=w.querySelector('.puck'),fill=w.querySelector('.stabBar i'),msg=w.querySelector('.stabText');let puckX=0,drag=false,acc=0,last=performance.now(),phase=0,penalty=false,jump=false,raf=0,zoneX=0,zoneW=108;function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function setPuck(x){puckX=clamp(x,29,arena.clientWidth-29);puck.style.left=(puckX-29)+'px'}requestAnimationFrame(()=>setPuck(arena.clientWidth/2));on(puck,'pointerdown',e=>{e.preventDefault();drag=true;puck.setPointerCapture?.(e.pointerId)});on(puck,'pointermove',e=>{if(!drag)return;let r=arena.getBoundingClientRect();setPuck(e.clientX-r.left)});on(puck,'pointerup',()=>drag=false);on(puck,'pointercancel',()=>drag=false);on(arena,'pointerdown',e=>{if(e.target===puck||puck.contains(e.target))return;let r=arena.getBoundingClientRect();setPuck(e.clientX-r.left)});function loop(t){let dt=Math.min(.04,(t-last)/1000);last=t;phase+=dt;let aw=arena.clientWidth;zoneW=acc>4.2?82:acc>2.1?96:112;let travel=Math.max(0,aw-zoneW-36);zoneX=18+travel*(.5+.46*Math.sin(phase*(acc>4?1.2:.85)))/1;zoneX=clamp(zoneX,18,aw-zoneW-18);zone.style.left=zoneX+'px';zone.style.width=zoneW+'px';let inside=puckX>zoneX+10&&puckX<zoneX+zoneW-10;if(inside){acc+=dt;msg.textContent='dentro la zona';}else{acc=Math.max(0,acc-dt*.28);msg.textContent='fuori dalla zona';}if(!penalty&&acc>2.7){penalty=true;acc=Math.max(0,acc-.55);fx('RICALIBRATO');msg.textContent='progresso ricalibrato';}if(!jump&&acc>4.5){jump=true;phase+=2.2;fx('ZONA SPOSTATA');}fill.style.width=Math.min(100,acc/6*100)+'%';metric.textContent=acc.toFixed(1)+' / 6.0s';if(acc>=6)return win('Stabilità completata.');raf=requestAnimationFrame(loop)}raf=requestAnimationFrame(loop);cleanups.push(()=>cancelAnimationFrame(raf))}

function l3(){hint.textContent='Scorri nella direzione mostrata.';metric.textContent='0 / 10';let w=document.createElement('div');w.className='swipeWrap';w.innerHTML='<div class="swipePrompt"><span>⬆️</span></div><div class="swipeCount">0 di 10</div>';stage.appendChild(w);let icon=w.querySelector('.swipePrompt span'),count=w.querySelector('.swipeCount'),sx=0,sy=0,n=0,stolen=false;const dirs=[{k:'U',e:'⬆️'},{k:'D',e:'⬇️'},{k:'L',e:'⬅️'},{k:'R',e:'➡️'}];let current=dirs[0];function next(){current=dirs[Math.floor(Math.random()*dirs.length)];icon.textContent=current.e}next();on(w,'pointerdown',e=>{e.preventDefault();sx=e.clientX;sy=e.clientY});on(w,'pointerup',e=>{let dx=e.clientX-sx,dy=e.clientY-sy;if(Math.hypot(dx,dy)<34)return fx('SWIPE TROPPO CORTO');let got=Math.abs(dx)>Math.abs(dy)?(dx>0?'R':'L'):(dy>0?'D':'U');if(got!==current.k)return fx('DIREZIONE ERRATA');n++;if(!stolen&&n===7){stolen=true;n=5;fx('INPUT DUPLICATO');}metric.textContent=n+' / 10';count.textContent=n+' di 10';if(n>=10)return win('Sequenza completata.');fx('OK',false);next()})}

function l4(){hint.textContent='Usa le quattro frecce. La casella arancione si apre e si chiude.';metric.textContent='0 urti';let wrap=document.createElement('div');wrap.className='mazeWrap';wrap.innerHTML='<div class="mazeBoard"></div><div class="mazeInfo">🟨 passa solo quando è aperta</div><div class="dpad"><button class="up">↑</button><button class="left">←</button><button class="down">↓</button><button class="right">→</button></div>';stage.appendChild(wrap);let board=wrap.querySelector('.mazeBoard'),info=wrap.querySelector('.mazeInfo');const grid=[[0,0,0,1,0,0,0],[1,1,0,1,0,1,0],[0,0,0,2,0,1,0],[0,1,1,1,0,0,0],[0,0,0,1,1,1,0],[0,1,0,0,0,0,0],[0,1,1,1,1,1,1]],R=7,C=7;let pos={r:6,c:0},goal={r:0,c:6},hits=0,gateOpen=true,gateTimer=0;board.style.gridTemplateColumns='repeat('+C+',1fr)';board.style.gridTemplateRows='repeat('+R+',1fr)';function draw(){board.innerHTML='';for(let r=0;r<R;r++)for(let c=0;c<C;c++){let d=document.createElement('div');d.className='mazeCell'+(grid[r][c]===1?' wall':'')+(grid[r][c]===2?' gate'+(gateOpen?'':' closed'):'');if(r===goal.r&&c===goal.c)d.innerHTML='<span>🚪</span>';if(r===pos.r&&c===pos.c)d.innerHTML='<span>🐸</span>';board.appendChild(d)}}draw();let interval=setInterval(()=>{gateOpen=!gateOpen;draw()},950);cleanups.push(()=>clearInterval(interval));function move(dr,dc){let nr=pos.r+dr,nc=pos.c+dc;if(nr<0||nr>=R||nc<0||nc>=C||grid[nr][nc]===1){hits++;metric.textContent=hits+' urti';return fx('MURO')}if(grid[nr][nc]===2&&!gateOpen){hits++;metric.textContent=hits+' urti';info.textContent='la casella arancione è chiusa';return fx('CHIUSO')}pos={r:nr,c:nc};draw();if(pos.r===goal.r&&pos.c===goal.c)return win('Uscita raggiunta.')}on(wrap.querySelector('.up'),'pointerdown',e=>{e.preventDefault();move(-1,0)});on(wrap.querySelector('.down'),'pointerdown',e=>{e.preventDefault();move(1,0)});on(wrap.querySelector('.left'),'pointerdown',e=>{e.preventDefault();move(0,-1)});on(wrap.querySelector('.right'),'pointerdown',e=>{e.preventDefault();move(0,1)})}

function l5(){hint.textContent='Tocca il bersaglio.';metric.textContent='0 / 12';let w=document.createElement('div');w.className='tapWrap';w.innerHTML='<div class="tapArena"><button class="tapOrb"><span>🎯</span></button><div class="tapInfo">centri: 0</div></div>';stage.appendChild(w);let arena=w.querySelector('.tapArena'),orb=w.querySelector('.tapOrb'),info=w.querySelector('.tapInfo'),n=0,taken=false;function place(){requestAnimationFrame(()=>{let aw=arena.clientWidth,ah=arena.clientHeight;orb.style.left=(12+Math.random()*Math.max(10,aw-98))+'px';orb.style.top=(12+Math.random()*Math.max(10,ah-98))+'px';let size=n>8?58:n>5?66:74;orb.style.width=size+'px';orb.style.height=size+'px'})}place();on(orb,'pointerdown',e=>{e.preventDefault();n++;if(!taken&&n===8){taken=true;n=6;fx('VERIFICA PUNTEGGIO');}metric.textContent=n+' / 12';info.textContent='centri: '+n;if(n>=12)return win('Precisione completata.');place()})}

function fakeWin(){show('fakeWin')}
$('#claimBtn').onclick=()=>{show('verify');let lines=[...document.querySelectorAll('#log div')];lines.forEach((x,i)=>later(()=>{x.classList.add('on');if(i===lines.length-1)later(()=>show('troll'),1000)},600*i+450))};
let accept=0;$('#acceptBtn').onclick=()=>{accept++;let b=$('#acceptBtn');if(accept===1)b.textContent='SICURA?';else if(accept===2)b.textContent='PROPRIO SICURA?';else if(accept===3)b.textContent='VA BENE, HO PERSO';else{b.textContent='REGISTRATO ✓';b.disabled=true;$('#softEnd').style.display='block'}};
renderProgress();
