/* 1 — ROSE RUSH */
function initRunner(){setHUD("01 // ROSE RUSH","0 / 18");setLives(3);tip.textContent="Scorri ↔️ · prendi 🌹 e 💋 · evita 💔";gestureHint.textContent="swipe sinistra / destra";state={lane:1,targetLane:1,x:W/2,y:H-112,score:0,lives:3,combo:0,items:[],spawn:.4,time:24,sx:0,sy:0};on(canvas,"pointerdown",e=>{let p=pos(e);state.sx=p.x;state.sy=p.y});on(canvas,"pointerup",e=>{let p=pos(e),dx=p.x-state.sx;if(Math.abs(dx)>32){state.targetLane=clamp(state.targetLane+(dx>0?1:-1),0,2);sfx("tap")}})}
function updateRunner(dt){state.time-=dt;if(state.time<=0)return lose(`Tempo finito a ${state.score} punti. Mancava poco.`);const lanes=[W*.22,W*.5,W*.78];state.x+=(lanes[state.targetLane]-state.x)*Math.min(1,dt*14);state.spawn-=dt;const elapsed=24-state.time;if(state.spawn<=0){state.spawn=Math.max(.28,.6-elapsed*.012);const r=Math.random();state.items.push({lane:Math.floor(Math.random()*3),y:88,type:r<.17?"bad":r<.63?"rose":"kiss",sp:150+elapsed*4+Math.random()*35})}for(let i=state.items.length-1;i>=0;i--){let a=state.items[i];a.y+=a.sp*dt;let x=lanes[a.lane];if(Math.abs(a.y-state.y)<32&&Math.abs(x-state.x)<44){state.items.splice(i,1);if(a.type==="bad"){state.lives--;state.combo=0;setLives(state.lives);flashBad();sfx("bad");if(state.lives<=0)return lose("Tre cuori rotti. Direi che possiamo rifarla.")}else{state.combo++;state.score+=a.type==="kiss"?2:1;if(state.combo>=5)state.score++;metric.textContent=state.score+" / 18";sfx("tap");if(state.score>=18)return win("18 punti. Rose salvate, bacini presi. Tutto in ordine.")}continue}if(a.y>H+40)state.items.splice(i,1)}for(let i=0;i<3;i++){ctx.strokeStyle="#ffffff0c";ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(lanes[i],78);ctx.lineTo(lanes[i],H-56);ctx.stroke()}state.items.forEach(a=>{let x=lanes[a.lane];circle(x,a.y,26,"#ffffff0b");emoji(a.type==="bad"?"💔":a.type==="rose"?"🌹":"💋",x,a.y,32)});avatar(state.x,state.y,20);txt("COMBO ×"+state.combo,16,H-48,11,state.combo>=5?"#ffd58e":"#8d818a","left",900)}

/* 2 — KISS PONG */
function initPong(){setHUD("02 // KISS PONG","12 cuori");setLives(3);tip.textContent="Trascina la racchetta · non far cadere 💋";gestureHint.textContent="trascina in basso";let bricks=[];const cols=4,rows=3,bw=(W-50)/cols;for(let r=0;r<rows;r++)for(let c=0;c<cols;c++)bricks.push({x:25+c*bw+4,y:115+r*52,w:bw-8,h:34,hp:1});state={paddle:{x:W/2,w:92,y:H-92},ball:{x:W/2,y:H*.58,vx:118,vy:-185,r:12},bricks,lives:3,cleared:0,drag:false};on(canvas,"pointerdown",e=>{let p=pos(e);state.drag=true;state.paddle.x=clamp(p.x,50,W-50)});on(canvas,"pointermove",e=>{if(state.drag)state.paddle.x=clamp(pos(e).x,50,W-50)});on(canvas,"pointerup",()=>state.drag=false);on(canvas,"pointercancel",()=>state.drag=false)}
function updatePong(dt){let b=state.ball,p=state.paddle;b.x+=b.vx*dt;b.y+=b.vy*dt;if(b.x<b.r){b.x=b.r;b.vx=Math.abs(b.vx)}if(b.x>W-b.r){b.x=W-b.r;b.vx=-Math.abs(b.vx)}if(b.y<88+b.r){b.y=88+b.r;b.vy=Math.abs(b.vy)}if(b.vy>0&&b.y+b.r>p.y-9&&b.y-b.r<p.y+9&&Math.abs(b.x-p.x)<p.w/2+6){b.y=p.y-12;b.vy=-Math.abs(b.vy)*1.025;b.vx+=(b.x-p.x)*4;let sp=Math.hypot(b.vx,b.vy);if(sp>330){b.vx*=330/sp;b.vy*=330/sp}sfx("tap")}for(const br of state.bricks){if(!br.hp)continue;if(b.x+b.r>br.x&&b.x-b.r<br.x+br.w&&b.y+b.r>br.y&&b.y-b.r<br.y+br.h){br.hp=0;state.cleared++;metric.textContent=(12-state.cleared)+" cuori";b.vy*=-1;sfx("tap");if(state.cleared===12)return win("Dodici cuori fatti. Il bacino è sopravvissuto.");break}}if(b.y>H+30){state.lives--;setLives(state.lives);flashBad();if(state.lives<=0)return lose("Tre bacini caduti. Questa fa un po' male.");b.x=W/2;b.y=H*.58;b.vx=(Math.random()>.5?1:-1)*130;b.vy=-190}state.bricks.forEach(br=>{if(!br.hp)return;rr(br.x,br.y,br.w,br.h,12);ctx.fillStyle="#ffffff0b";ctx.fill();ctx.strokeStyle="#ff9cbd33";ctx.stroke();emoji("❤️",br.x+br.w/2,br.y+br.h/2,20)});rr(p.x-p.w/2,p.y-8,p.w,16,8);ctx.fillStyle="#ff91b7";ctx.fill();circle(b.x,b.y,18,"#ff8eb415");emoji("💋",b.x,b.y,24)}

/* 3 — COSTELLAZIONE */
function initConstellation(){setHUD("03 // COSTELLAZIONE","1 / 3");setLives(3);tip.textContent="Tieni premuto e collega i cuori nell'ordine";gestureHint.textContent="trascina senza staccare";state={round:1,lives:3,nodes:makeNodes(5),haz:makeHazards(2),drag:false,next:0,path:[],pointer:{x:0,y:0},cool:0};on(canvas,"pointerdown",e=>{state.drag=true;state.pointer=pos(e);state.path=[state.pointer]});on(canvas,"pointermove",e=>{if(state.drag){state.pointer=pos(e);state.path.push(state.pointer);if(state.path.length>90)state.path.shift()}});on(canvas,"pointerup",()=>{state.drag=false;state.path=[]});on(canvas,"pointercancel",()=>{state.drag=false;state.path=[]})}
function makeNodes(n){const arr=[];let tries=0;while(arr.length<n&&tries++<300){let x=48+Math.random()*(W-96),y=150+Math.random()*(H-320);if(arr.every(a=>Math.hypot(a.x-x,a.y-y)>74))arr.push({x,y,r:20,hit:false,id:arr.length+1})}while(arr.length<n){let i=arr.length;arr.push({x:60+(i%3)*(W-120)/2,y:170+Math.floor(i/3)*95,r:20,hit:false,id:i+1})}return arr}
function makeHazards(n){const arr=[];for(let i=0;i<n;i++)arr.push({x:70+Math.random()*(W-140),y:180+Math.random()*(H-360),r:18,vx:(Math.random()>.5?1:-1)*(45+Math.random()*35),vy:(Math.random()>.5?1:-1)*(30+Math.random()*25)});return arr}
function resetConstellationRound(){state.nodes=makeNodes(4+state.round);state.haz=makeHazards(1+state.round);state.next=0;state.path=[];state.drag=false;tip.textContent="Nuova costellazione ✦"}
function updateConstellation(dt){state.cool=Math.max(0,state.cool-dt);state.haz.forEach(h=>{h.x+=h.vx*dt;h.y+=h.vy*dt;if(h.x<h.r||h.x>W-h.r)h.vx*=-1;if(h.y<120+h.r||h.y>H-70-h.r)h.vy*=-1});if(state.drag){const p=state.pointer;const target=state.nodes[state.next];if(target&&Math.hypot(p.x-target.x,p.y-target.y)<target.r+12){target.hit=true;state.next++;sfx("tap");if(state.next===state.nodes.length){if(state.round===3)return win("Tre costellazioni complete. Questa te la concedo bella.");state.round++;metric.textContent=state.round+" / 3";setTimeout(()=>{if(active)resetConstellationRound()},220)}}if(state.cool<=0&&state.haz.some(h=>Math.hypot(p.x-h.x,p.y-h.y)<h.r+10)){state.lives--;setLives(state.lives);state.cool=.55;flashBad();sfx("bad");if(state.lives<=0)return lose("Tre cuori rotti toccati. Riproviamo con più calma.")}}if(state.path.length>1){ctx.strokeStyle="#ff9fc1aa";ctx.lineWidth=5;ctx.lineCap="round";ctx.beginPath();ctx.moveTo(state.path[0].x,state.path[0].y);for(let i=1;i<state.path.length;i++)ctx.lineTo(state.path[i].x,state.path[i].y);ctx.stroke()}state.nodes.forEach((n,i)=>{circle(n.x,n.y,n.r+9,n.hit?"#a8ffcf16":"#ff78a714");emoji(n.hit?"💗":"❤️",n.x,n.y,27);txt(String(i+1),n.x,n.y+32,10,n.hit?"#8fcdb0":"#b9adb6")});state.haz.forEach(h=>{circle(h.x,h.y,h.r+9,"#ff4f7811");emoji("💔",h.x,h.y,26)});if(state.drag)circle(state.pointer.x,state.pointer.y,7,"#fff")}

/* 4 — RHYTHM */
function initRhythm(){setHUD("04 // RITMO","0%");setLives(3);tip.textContent="Tocca la corsia quando la nota arriva sulla linea rosa";gestureHint.textContent="4 corsie · tocca";state={notes:[],spawn:.45,elapsed:0,total:0,good:0,lives:3,combo:0,maxNotes:28,speed:220};on(canvas,"pointerdown",e=>{let p=pos(e),lane=clamp(Math.floor(p.x/(W/4)),0,3),lineY=H-128,best=-1,bd=999;for(let i=0;i<state.notes.length;i++){let n=state.notes[i];if(n.lane!==lane||n.hit)continue;let d=Math.abs(n.y-lineY);if(d<bd){bd=d;best=i}}if(best>=0&&bd<58){let n=state.notes[best];n.hit=true;state.good++;state.combo++;sfx("tap");if(bd<20)state.good+=.18}else{state.combo=0;state.lives--;setLives(state.lives);flashBad();if(state.lives<=0)return lose("Tre tap fuori tempo. Questa richiede un po' di ritmo.")}metric.textContent=Math.round(state.good/Math.max(1,state.total)*100)+"%"})}
function updateRhythm(dt){state.elapsed+=dt;state.spawn-=dt;if(state.spawn<=0&&state.total<state.maxNotes){state.spawn=.42+Math.random()*.26;state.notes.push({lane:Math.floor(Math.random()*4),y:92,hit:false});state.total++}const lineY=H-128;for(let i=state.notes.length-1;i>=0;i--){let n=state.notes[i];n.y+=state.speed*dt;if(n.y>lineY+65){if(!n.hit)state.combo=0;state.notes.splice(i,1)}}if(state.total===state.maxNotes&&state.notes.length===0){let acc=state.good/state.maxNotes;if(acc>=.75)return win(`Precisione ${Math.round(acc*100)}%. Direi che il ritmo c'è.`);return lose(`Precisione ${Math.round(acc*100)}%. Serve almeno il 75%.`)}for(let i=0;i<4;i++){ctx.fillStyle=i%2?"#ffffff03":"#ffffff05";ctx.fillRect(i*W/4,74,W/4,H-74);ctx.strokeStyle="#ffffff09";ctx.beginPath();ctx.moveTo(i*W/4,80);ctx.lineTo(i*W/4,H);ctx.stroke()}ctx.strokeStyle="#ff7fab";ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(0,lineY);ctx.lineTo(W,lineY);ctx.stroke();state.notes.forEach(n=>{if(n.hit)return;let x=(n.lane+.5)*W/4;circle(x,n.y,23,"#ff92b719");emoji(["💗","🌹","💋","✨"][n.lane],x,n.y,29)});txt("COMBO ×"+state.combo,16,105,11,state.combo>=5?"#ffd58e":"#8f838c","left",900)}

/* 5 — VAULT */
function initVault(){setHUD("05 // CASSAFORTE","1 / 3");setLives(3);tip.textContent="Trascina l'anello evidenziato fino al simbolo giusto";gestureHint.textContent="trascina attorno al centro";state={round:1,lives:3,activeRing:0,angles:[0,0,0],targets:newTargets(),drag:false,lastA:0,hold:0};on(canvas,"pointerdown",e=>{let p=pos(e),dx=p.x-W/2,dy=p.y-H*.5,r=Math.hypot(dx,dy);state.activeRing=r<82?0:r<126?1:2;state.drag=true;state.lastA=Math.atan2(dy,dx)});on(canvas,"pointermove",e=>{if(!state.drag)return;let p=pos(e),a=Math.atan2(p.y-H*.5,p.x-W/2),da=a-state.lastA;if(da>Math.PI)da-=Math.PI*2;if(da<-Math.PI)da+=Math.PI*2;state.angles[state.activeRing]+=da;state.lastA=a});on(canvas,"pointerup",()=>vaultRelease());on(canvas,"pointercancel",()=>vaultRelease())}
function vaultRelease(){if(!state||level!==5)return;state.drag=false;if(state.activeRing<3&&state.hold<.18&&angleDiff(state.angles[state.activeRing],state.targets[state.activeRing])>.38){state.lives--;setLives(state.lives);flashBad();sfx("bad");if(state.lives<=0)return lose("Tre tentativi fuori combinazione. La cassaforte resta chiusa.");tip.textContent="Quasi: riposiziona l’anello e riprova."}}
function newTargets(){return[0,1,2].map(()=>Math.floor(Math.random()*8)*(Math.PI/4))}
function angleDiff(a,b){let d=(a-b)%(Math.PI*2);if(d>Math.PI)d-=Math.PI*2;if(d<-Math.PI)d+=Math.PI*2;return Math.abs(d)}
function updateVault(dt){const cx=W/2,cy=H*.5,rads=[60,102,144],symbols=["💋","🌹","💗","✨","🌙","⭐","🫶","🌸"],colors=["#ff8fb5","#ffd58e","#cbb4ff"];let ok=angleDiff(state.angles[state.activeRing],state.targets[state.activeRing])<.11;if(ok)state.hold+=dt;else state.hold=Math.max(0,state.hold-dt*.6);if(state.hold>1.0){state.angles[state.activeRing]=state.targets[state.activeRing];state.activeRing++;state.hold=0;sfx("tap");if(state.activeRing>=3){if(state.round===3)return win("Tre combinazioni aperte. La cassaforte si arrende.");state.round++;metric.textContent=state.round+" / 3";state.activeRing=0;state.angles=[0,0,0];state.targets=newTargets();tip.textContent="Nuova combinazione 🔐"}}for(let i=0;i<3;i++){ctx.beginPath();ctx.arc(cx,cy,rads[i],0,Math.PI*2);ctx.strokeStyle=i===state.activeRing?colors[i]:"#ffffff12";ctx.lineWidth=i===state.activeRing?12:8;ctx.stroke();for(let k=0;k<8;k++){let a=k*Math.PI/4+state.angles[i],x=cx+Math.cos(a)*rads[i],y=cy+Math.sin(a)*rads[i];emoji(symbols[k],x,y,17)}let ta=state.targets[i],tx=cx+Math.cos(ta)*rads[i],ty=cy+Math.sin(ta)*rads[i];circle(tx,ty,9,i<state.activeRing?"#a8ffcf":"#ffffff")}circle(cx,cy,34,"#ffffff08");emoji("🔐",cx,cy,31);if(state.activeRing<3){txt("tieni fermo",cx,cy+185,11,"#92858e");rr(cx-70,cy+204,140,8,4);ctx.fillStyle="#ffffff0c";ctx.fill();rr(cx-70,cy+204,140*clamp(state.hold,0,1),8,4);ctx.fillStyle="#ff8fb5";ctx.fill()}}
