"use strict";
const $=s=>document.querySelector(s),screens=[...document.querySelectorAll('.screen')],game=$('#game'),stage=$('#gameStage'),metric=$('#metric');
let hint=$('#hint'),level=1,unlocked=Math.max(1,Math.min(6,+localStorage.getItem('amelieV17Unlocked')||1)),cleanups=[],timers=[];
const defs=[
 {title:'Continua',desc:'Premi il pulsante per completare il livello.'},
 {title:'Stabilità',desc:'Usa lo slider per mantenere 😇 dentro la zona verde per 7 secondi totali.'},
 {title:'Sequenza',desc:'Memorizza le direzioni e ripetile nell’ordine corretto.'},
 {title:'Labirinto',desc:'Usa le frecce per portare 🐸 fino a 🚪.'},
 {title:'Precisione',desc:'Tocca il bersaglio 15 volte.'}
];
function show(id){screens.forEach(s=>s.classList.remove('on'));game.classList.remove('on');$('#'+id).classList.add('on')}
function renderProgress(){let p=$('#progress');p.innerHTML='';for(let i=1;i<=5;i++){let d=document.createElement('div');d.className='step'+(i<unlocked?' done':i===unlocked?' now':'');d.textContent=String(i).padStart(2,'0');p.appendChild(d)}$('#startBtn').textContent=unlocked>1&&unlocked<=5?'CONTINUA':'INIZIA'}
function intro(n){level=n;show('intro');$('#introNo').textContent=String(n).padStart(2,'0');$('#introTitle').textContent=defs[n-1].title;$('#introDesc').textContent=defs[n-1].desc}
function clean(){cleanups.forEach(f=>{try{f()}catch{}});cleanups=[];timers.forEach(clearTimeout);timers=[];stage.innerHTML='<div class="hint" id="hint"></div>';hint=$('#hint')}
function later(fn,ms){let id=setTimeout(fn,ms);timers.push(id);return id}
function on(el,ev,fn,opt){el.addEventListener(ev,fn,opt);cleanups.push(()=>el.removeEventListener(ev,fn,opt))}
function feedback(text,kind='soft'){
 const toast=$('#softToast');
 if(kind==='soft'){toast.classList.remove('go');void toast.offsetWidth;toast.textContent=text;toast.classList.add('go');navigator.vibrate?.(18);return}
 let f=$('#errorFlash'),t=$('#errorText');f.className='errorFlash '+(kind==='bad'?'bad':'good');f.classList.remove('go');t.classList.remove('go');void f.offsetWidth;f.classList.add('go');t.textContent=text;t.classList.add('go');if(kind==='bad'){stage.classList.remove('shake');void stage.offsetWidth;stage.classList.add('shake');navigator.vibrate?.([45,25,55])}else navigator.vibrate?.(20)
}
function start(){clean();screens.forEach(s=>s.classList.remove('on'));game.classList.add('on');$('#stageLabel').textContent='LIVELLO '+String(level).padStart(2,'0');[l1,l2,l3,l4,l5][level-1]()}
function win(text){unlocked=Math.max(unlocked,level<5?level+1:6);localStorage.setItem('amelieV17Unlocked',unlocked);$('#resultTitle').textContent='Completato';$('#resultText').textContent=text;$('#resultBtn').textContent=level===5?'VEDI RISULTATO':'CONTINUA';$('#resultBtn').onclick=()=>{$('#result').classList.remove('on');clean();level===5?fakeWin():intro(level+1)};$('#result').classList.add('on')}
$('#startBtn').onclick=()=>intro(Math.min(unlocked,5));$('#resetBtn').onclick=()=>{localStorage.removeItem('amelieV17Unlocked');unlocked=1;renderProgress()};$('#playBtn').onclick=start;

function l1(){hint.textContent='Premi CONTINUA.';metric.textContent='0 / 11';let area=document.createElement('div');area.className='escapeArea';let b=document.createElement('button');b.className='escapeBtn';b.textContent='CONTINUA';let stat=document.createElement('div');stat.className='attempt';stat.textContent='tentativi: 0';area.append(b,stat);stage.appendChild(area);let n=0,final=false,extra=0,decoys=[];function place(el=b){requestAnimationFrame(()=>{let w=area.clientWidth,h=area.clientHeight,bw=Math.max(145,el.offsetWidth||145),bh=Math.max(55,el.offsetHeight||55);el.style.transform='none';el.style.left=(12+Math.random()*Math.max(8,w-bw-24))+'px';el.style.top=(14+Math.random()*Math.max(8,h-bh-45))+'px'})}b.style.left='50%';b.style.top='44%';b.style.transform='translate(-50%,-50%)';function addDecoys(){if(decoys.length)return;for(let i=0;i<2;i++){let d=document.createElement('button');d.className='escapeBtn fake';d.textContent='CONTINUA';area.appendChild(d);place(d);on(d,'pointerdown',e=>{e.preventDefault();feedback('Pulsante non valido','bad');place(d)});decoys.push(d)}}on(b,'pointerdown',e=>{e.preventDefault();if(final){extra++;if(extra===1){feedback('Verifica in corso');b.textContent='ATTENDI';later(()=>{b.textContent='CONTINUA';place()},430);return}if(extra===2){feedback('Posizione aggiornata');place();return}return win('Livello completato.')}n++;metric.textContent=n+' / 11';stat.textContent='tentativi: '+n;feedback(['Mancato','Riprova','Quasi','Ancora','Riprova','Quasi','Mancato','Riprova','Quasi','Ancora','Ok'][Math.min(n-1,10)]);if(n===5)addDecoys();if(n===8)b.textContent='CONTINUA →';if(n>=11){final=true;decoys.forEach(x=>x.remove());b.textContent='CONTINUA';b.style.left='50%';b.style.top='50%';b.style.transform='translate(-50%,-50%)';b.style.background='var(--green)';b.style.color='#12351d'}else{place();if(n>=7)later(()=>place(),130)}})}

function l2(){hint.textContent='Muovi lo slider. Il centro di 😇 deve restare dentro la zona verde.';metric.textContent='0.0 / 7.0s';let w=document.createElement('div');w.className='stabilizer';w.innerHTML='<div class="stabArena"><div class="safeZone"></div><div class="puck"><span>😇</span></div></div><div class="stabBar"><i></i></div><div class="stabText">usa lo slider qui sotto</div><div class="sliderBox"><div class="sliderTrack"><button class="sliderThumb" aria-label="slider"><span>↔️</span></button></div></div>';stage.appendChild(w);let arena=w.querySelector('.stabArena'),zone=w.querySelector('.safeZone'),puck=w.querySelector('.puck'),fill=w.querySelector('.stabBar i'),msg=w.querySelector('.stabText'),track=w.querySelector('.sliderTrack'),thumb=w.querySelector('.sliderThumb');let pos=.5,drag=false,acc=0,last=performance.now(),phase=0,pen1=false,pen2=false,raf=0;function setPos(v){pos=Math.max(0,Math.min(1,v));thumb.style.left=(pos*100)+'%';let aw=arena.clientWidth;puck.style.left=(30+pos*Math.max(0,aw-60))+'px'}function pointerToPos(e){let r=track.getBoundingClientRect();setPos((e.clientX-r.left)/r.width)}requestAnimationFrame(()=>setPos(.5));on(thumb,'pointerdown',e=>{e.preventDefault();drag=true;thumb.setPointerCapture?.(e.pointerId)});on(thumb,'pointermove',e=>{if(drag)pointerToPos(e)});on(thumb,'pointerup',()=>drag=false);on(thumb,'pointercancel',()=>drag=false);on(track,'pointerdown',e=>{if(e.target===thumb||thumb.contains(e.target))return;pointerToPos(e)});function loop(t){let dt=Math.min(.04,(t-last)/1000);last=t;phase+=dt;let aw=arena.clientWidth,zoneW=acc>5?74:acc>3?84:98;let travel=aw-zoneW-34;let speed=acc>5?1.65:acc>3?1.35:1.05;let zx=17+travel*(.5+.48*Math.sin(phase*speed));zone.style.left=zx+'px';zone.style.width=zoneW+'px';let px=30+pos*Math.max(0,aw-60),inside=px>zx+9&&px<zx+zoneW-9;if(inside){acc+=dt;msg.textContent='stabile';}else{acc=Math.max(0,acc-dt*.42);msg.textContent='fuori zona';}if(!pen1&&acc>2.7){pen1=true;acc=Math.max(0,acc-.45);feedback('Calibrazione aggiornata');}if(!pen2&&acc>5.15){pen2=true;phase+=1.7;feedback('Zona riallineata');}fill.style.width=Math.min(100,acc/7*100)+'%';metric.textContent=acc.toFixed(1)+' / 7.0s';if(acc>=7)return win('Stabilità completata.');raf=requestAnimationFrame(loop)}raf=requestAnimationFrame(loop);cleanups.push(()=>cancelAnimationFrame(raf))}

function l3(){hint.textContent='Memorizza la sequenza. Poi ripetila con i quattro tasti.';metric.textContent='ROUND 1 / 5';let w=document.createElement('div');w.className='sequenceWrap';w.innerHTML='<div class="sequenceCard"><div class="sequenceLabel">MEMORIZZA</div><div class="sequenceDisplay"></div><div class="sequencePrompt">preparati…</div></div><div class="sequenceDots"></div><div class="seqPad"><button data-k="U">↑</button><button data-k="L">←</button><button data-k="D">↓</button><button data-k="R">→</button></div>';stage.appendChild(w);let display=w.querySelector('.sequenceDisplay'),label=w.querySelector('.sequenceLabel'),prompt=w.querySelector('.sequencePrompt'),dots=w.querySelector('.sequenceDots'),buttons=[...w.querySelectorAll('.seqPad button')];const symbols={U:'↑',D:'↓',L:'←',R:'→'},keys=['U','D','L','R'];let round=1,seq=[],input=[],locked=true,penaltyUsed=false;function makeSeq(){let len=[3,4,4,5,6][round-1];seq=Array.from({length:len},()=>keys[Math.floor(Math.random()*4)]);input=[];metric.textContent='ROUND '+round+' / 5';dots.innerHTML='';for(let i=0;i<5;i++){let d=document.createElement('i');if(i<round-1)d.className='on';dots.appendChild(d)}showSeq()}function showSeq(){locked=true;label.textContent='MEMORIZZA';prompt.textContent='';display.innerHTML='';seq.forEach(k=>{let a=document.createElement('div');a.className='seqArrow';a.textContent=symbols[k];display.appendChild(a)});let delay=round>=4?950:1150;later(()=>{display.innerHTML='';label.textContent='RIPETI';prompt.textContent=seq.length+' direzioni';locked=false},delay)}function wrong(){locked=true;feedback('Sequenza errata','bad');prompt.textContent='riprova lo stesso round';later(showSeq,620)}function press(k){if(locked)return;input.push(k);let idx=input.length-1;if(k!==seq[idx])return wrong();prompt.textContent=input.length+' / '+seq.length;if(input.length===seq.length){locked=true;if(round===4&&!penaltyUsed){penaltyUsed=true;feedback('Conferma richiesta');prompt.textContent='sequenza da riconfermare';later(showSeq,650);return}feedback('Corretto','soft');if(round>=5)return later(()=>win('Sequenze completate.'),420);round++;later(makeSeq,520)}}buttons.forEach(b=>on(b,'pointerdown',e=>{e.preventDefault();press(b.dataset.k)}));makeSeq()}

function l4(){hint.textContent='Usa le frecce. Le caselle gialle sono porte temporizzate.';metric.textContent='0 errori';let wrap=document.createElement('div');wrap.className='mazeWrap';wrap.innerHTML='<div class="mazeBoard"></div><div class="mazeInfo">le porte si aprono e si chiudono</div><div class="dpad"><button class="up">↑</button><button class="left">←</button><button class="down">↓</button><button class="right">→</button></div>';stage.appendChild(wrap);let board=wrap.querySelector('.mazeBoard'),info=wrap.querySelector('.mazeInfo');
const grid=[
 [0,1,0,0,0,1,0,0,0],
 [0,1,0,1,0,1,0,1,0],
 [0,0,0,1,0,0,0,1,0],
 [1,1,0,1,1,1,0,1,0],
 [0,0,0,0,4,0,0,0,0],
 [0,1,1,1,0,1,1,1,0],
 [0,0,0,2,0,0,0,1,0],
 [0,1,0,1,1,1,0,3,0],
 [0,0,0,0,0,0,0,0,0]
],R=9,C=9;let pos={r:8,c:0},goal={r:0,c:8},errors=0,streak=0,cp={r:8,c:0},gateA=true,gateB=false;board.style.gridTemplateColumns='repeat('+C+',1fr)';board.style.gridTemplateRows='repeat('+R+',1fr)';function draw(){board.innerHTML='';for(let r=0;r<R;r++)for(let c=0;c<C;c++){let v=grid[r][c],d=document.createElement('div');d.className='mazeCell'+(v===1?' wall':'')+(v===2?' gateA'+(gateA?'':' closed'):'')+(v===3?' gateB'+(gateB?'':' closed'):'')+(v===4?' checkpoint':'');if(r===goal.r&&c===goal.c)d.innerHTML='<span>🚪</span>';else if(r===pos.r&&c===pos.c)d.innerHTML='<span>🐸</span>';else if(v===4)d.innerHTML='<span>💾</span>';board.appendChild(d)}}draw();let ia=setInterval(()=>{gateA=!gateA;draw()},850),ib=setInterval(()=>{gateB=!gateB;draw()},1150);cleanups.push(()=>clearInterval(ia),()=>clearInterval(ib));function bump(msg){errors++;streak++;metric.textContent=errors+' errori';feedback(msg,streak>=3?'bad':'soft');if(streak>=3){streak=0;pos={...cp};info.textContent='riparti dall’ultimo checkpoint';draw()}}function move(dr,dc){let nr=pos.r+dr,nc=pos.c+dc;if(nr<0||nr>=R||nc<0||nc>=C||grid[nr][nc]===1)return bump('Muro');if(grid[nr][nc]===2&&!gateA)return bump('Porta chiusa');if(grid[nr][nc]===3&&!gateB)return bump('Porta chiusa');pos={r:nr,c:nc};streak=0;if(grid[nr][nc]===4){cp={...pos};info.textContent='checkpoint salvato';feedback('Checkpoint','soft')}else info.textContent='';draw();if(pos.r===goal.r&&pos.c===goal.c)return win('Uscita raggiunta.')}on(wrap.querySelector('.up'),'pointerdown',e=>{e.preventDefault();move(-1,0)});on(wrap.querySelector('.down'),'pointerdown',e=>{e.preventDefault();move(1,0)});on(wrap.querySelector('.left'),'pointerdown',e=>{e.preventDefault();move(0,-1)});on(wrap.querySelector('.right'),'pointerdown',e=>{e.preventDefault();move(0,1)})}

function l5(){hint.textContent='Tocca il bersaglio.';metric.textContent='0 / 15';let w=document.createElement('div');w.className='tapWrap';w.innerHTML='<div class="tapArena"><button class="tapOrb"><span>🎯</span></button><div class="tapInfo">centri: 0</div></div>';stage.appendChild(w);let arena=w.querySelector('.tapArena'),orb=w.querySelector('.tapOrb'),info=w.querySelector('.tapInfo'),n=0,taken=false,ghostUsed=false;function place(){requestAnimationFrame(()=>{let aw=arena.clientWidth,ah=arena.clientHeight,size=n>11?54:n>7?62:74;orb.style.width=size+'px';orb.style.height=size+'px';orb.style.left=(12+Math.random()*Math.max(10,aw-size-24))+'px';orb.style.top=(12+Math.random()*Math.max(10,ah-size-24))+'px'})}function ghost(){if(ghostUsed)return;ghostUsed=true;let g=document.createElement('button');g.className='tapGhost';g.textContent='🎯';arena.appendChild(g);g.style.left='22%';g.style.top='40%';on(g,'pointerdown',e=>{e.preventDefault();n=Math.max(0,n-1);metric.textContent=n+' / 15';info.textContent='centri: '+n;feedback('Bersaglio inattivo','bad');g.remove()});later(()=>g.remove(),2600)}place();on(orb,'pointerdown',e=>{e.preventDefault();n++;if(!taken&&n===10){taken=true;n=8;feedback('Verifica punteggio');}if(n===6)ghost();metric.textContent=n+' / 15';info.textContent='centri: '+n;if(n>=15)return win('Precisione completata.');place()})}

function confetti(){for(let i=0;i<42;i++){let c=document.createElement('div');c.className='confetti';c.style.left=Math.random()*100+'vw';c.style.top=(-20-Math.random()*80)+'px';c.style.background=['#315efb','#78e2b3','#f0b85b','#7b61ff','#ef5964'][i%5];c.style.animationDelay=(Math.random()*.8)+'s';document.body.appendChild(c);later(()=>c.remove(),3600)}}
function fakeWin(){show('fakeWin');confetti()}
$('#claimBtn').onclick=()=>{show('verify');let lines=[...document.querySelectorAll('#log div')];lines.forEach((x,i)=>later(()=>{x.classList.add('on');if(i===lines.length-1)later(beginOverride,850)},520*i+360))};
function beginOverride(){show('override');$('#scoreAmelie').textContent='5';$('#scoreMusino').textContent='0';$('#overrideStamp').classList.remove('on');later(()=>{$('#scoreAmelie').textContent='0';$('#scoreMusino').textContent='1';$('#overrideStamp').classList.add('on');navigator.vibrate?.([80,40,100])},1050);later(()=>show('troll'),2450)}
let accept=0;$('#acceptBtn').onclick=()=>{accept++;let b=$('#acceptBtn');if(accept===1)b.textContent='SÌ, HO CAPITO';else if(accept===2)b.textContent='MUSINO HA VINTO';else if(accept===3)b.textContent='REGISTRA LA SCONFITTA';else{b.textContent='REGISTRATO ✓';b.disabled=true;$('#registered').style.display='block';$('#softEnd').style.display='block';navigator.vibrate?.([40,40,80])}};
renderProgress();
