/* AMELIE GAME V2 — 5 GIOCHI NUOVI */
let gv={down:null,move:null,up:null};
function clearGestures(){if(gv.down)canvas.removeEventListener('pointerdown',gv.down);if(gv.move)canvas.removeEventListener('pointermove',gv.move);if(gv.up){canvas.removeEventListener('pointerup',gv.up);canvas.removeEventListener('pointercancel',gv.up)}gv={down:null,move:null,up:null};if(canvasHandler){canvas.removeEventListener('pointerdown',canvasHandler);canvasHandler=null}}
function gestures(d,m,u){clearGestures();gv.down=d||null;gv.move=m||null;gv.up=u||null;if(d)canvas.addEventListener('pointerdown',d,{passive:false});if(m)canvas.addEventListener('pointermove',m,{passive:false});if(u){canvas.addEventListener('pointerup',u,{passive:false});canvas.addEventListener('pointercancel',u,{passive:false})}}
function resetJoy(){}
function pxy(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
function loseLife(msg){state.lives--;setLives(state.lives);game.classList.remove('shake');void game.offsetWidth;game.classList.add('shake');if(state.lives<=0){clearGestures();lose(msg);return true}return false}

/* 01 — SWIPE DEI BACINI */
const dirs=[{k:'L',a:'←',x:-1,y:0},{k:'R',a:'→',x:1,y:0},{k:'U',a:'↑',x:0,y:-1},{k:'D',a:'↓',x:0,y:1}];
function initSwipe(){setHUD('01 // BACINO AL VOLO','0 / 9');setLives(3);tip.textContent='Scorri il dito nella direzione indicata 💋';state={score:0,lives:3,dir:dirs[0],sx:0,sy:0,flash:0};nextSwipe();gestures(e=>{e.preventDefault();let p=pxy(e);state.sx=p.x;state.sy=p.y},null,e=>{e.preventDefault();let p=pxy(e),dx=p.x-state.sx,dy=p.y-state.sy;if(Math.hypot(dx,dy)<34)return;let got=Math.abs(dx)>Math.abs(dy)?(dx>0?'R':'L'):(dy>0?'D':'U');if(got===state.dir.k){state.score++;metric.textContent=state.score+' / 9';state.flash=.15;if(state.score>=9){clearGestures();return win('Nove bacini presi al volo. Direi bene. 💋')}nextSwipe()}else{if(loseLife('Tre swipe dalla parte sbagliata. Le indicazioni erano abbastanza grandi.'))return;nextSwipe()}})}
function nextSwipe(){let old=state.dir.k;do{state.dir=dirs[Math.floor(Math.random()*dirs.length)]}while(state.dir.k===old&&Math.random()<.65)}
function updateSwipe(dt){state.flash=Math.max(0,state.flash-dt);circle(W/2,H*.46,92,state.flash?'#ff78a724':'#ffffff08');emoji('💋',W/2,H*.43,82);txt(state.dir.a,W/2,H*.57,58,'#fff','center',800);txt('swipe',W/2,H*.66,12,'#a99ba8','center',700)}

/* 02 — RACCOGLI LE ROSE */
function initBouquet(){setHUD('02 // IL MAZZO','0 / 10');setLives(3);tip.textContent='Trascina il cestino · prendi 🌹 · evita 🥀';state={score:0,lives:3,basket:{x:W/2,y:H-105},items:[],spawn:.25,time:24};gestures(e=>{e.preventDefault();state.basket.x=pxy(e).x},e=>{e.preventDefault();state.basket.x=pxy(e).x},null)}
function spawnFlower(){let bad=Math.random()<.25;state.items.push({x:30+Math.random()*(W-60),y:90,v:145+Math.random()*75,bad,r:18,spin:(Math.random()-.5)*2})}
function updateBouquet(dt){state.time-=dt;state.spawn-=dt;if(state.time<=0){clearGestures();return lose('Il tempo è finito prima del mazzo. Riproviamo.')}if(state.spawn<=0){state.spawn=.38+Math.random()*.24;spawnFlower()}state.basket.x=Math.max(35,Math.min(W-35,state.basket.x));let by=state.basket.y;for(let i=state.items.length-1;i>=0;i--){let a=state.items[i];a.y+=a.v*dt;if(Math.abs(a.x-state.basket.x)<38&&Math.abs(a.y-by)<34){state.items.splice(i,1);if(a.bad){if(loseLife('Hai messo tre rose appassite nel mazzo. Musino non approva.'))return}else{state.score++;metric.textContent=state.score+' / 10';if(state.score>=10){clearGestures();return win('Mazzo completo. Questo almeno non appassisce. 🌹')}}continue}if(a.y>H-48){state.items.splice(i,1);if(!a.bad&&loseLife('Tre rose lasciate cadere. Molto romantico.'))return}}state.items.forEach(a=>emoji(a.bad?'🥀':'🌹',a.x,a.y,36));circle(state.basket.x,by+5,35,'#ffffff09');emoji('🧺',state.basket.x,by,54);txt(Math.max(0,state.time).toFixed(1)+'s',W/2,95,11,'#a99ba8')}

/* 03 — COLLEGA I CUORI */
function linkLayout(){return[{x:W*.18,y:H*.72},{x:W*.72,y:H*.66},{x:W*.30,y:H*.54},{x:W*.78,y:H*.43},{x:W*.22,y:H*.33},{x:W*.62,y:H*.22}]}
function hazardLayout(){return[{x:W*.49,y:H*.66,r:24},{x:W*.52,y:H*.50,r:27},{x:W*.47,y:H*.35,r:24}]}
function initLink(){setHUD('03 // FILO ROSA','1 → 6');setLives(3);tip.textContent='Tieni premuto e collega ❤️ da 1 a 6 senza toccare 💔';state={lives:3,nodes:linkLayout(),haz:hazardLayout(),next:0,drawing:false,path:[],flash:0};gestures(e=>{e.preventDefault();let p=pxy(e),n=state.nodes[0];if(Math.hypot(p.x-n.x,p.y-n.y)<34){state.drawing=true;state.next=1;state.path=[p]}},e=>{if(!state.drawing)return;e.preventDefault();let p=pxy(e);state.path.push(p);if(state.haz.some(h=>Math.hypot(p.x-h.x,p.y-h.y)<h.r+8)){state.drawing=false;state.path=[];state.next=0;if(loseLife('Hai toccato un 💔. Il percorso era quasi carino.'))return}let n=state.nodes[state.next];if(n&&Math.hypot(p.x-n.x,p.y-n.y)<31){state.next++;metric.textContent=Math.min(6,state.next)+' → 6';if(state.next>=6){clearGestures();return win('Collegati tutti. Nessun cuore rotto nel tragitto. ❤️')}}},e=>{if(state.drawing&&state.next<6){state.drawing=false;state.path=[];state.next=0;metric.textContent='1 → 6'}})}
function updateLink(){ctx.lineCap='round';if(state.path.length>1){ctx.strokeStyle='#ff8eb4';ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(state.path[0].x,state.path[0].y);for(let i=1;i<state.path.length;i++)ctx.lineTo(state.path[i].x,state.path[i].y);ctx.stroke()}state.haz.forEach(h=>{circle(h.x,h.y,h.r+7,'#ff4f7810');emoji('💔',h.x,h.y,38)});state.nodes.forEach((n,i)=>{circle(n.x,n.y,29,i<state.next?'#ff78a727':'#ffffff09');emoji('❤️',n.x,n.y,36);txt(String(i+1),n.x,n.y+39,11,i<state.next?'#ffb1ca':'#a99ba8')})}

/* 04 — RITMO */
function initRhythm(){setHUD('04 // A TEMPO','0 / 14');setLives(3);tip.textContent='Tocca una delle 3 corsie quando il simbolo arriva sulla linea';state={score:0,lives:3,notes:[],spawn:.25,time:25,lanes:[W*.23,W*.5,W*.77],hitY:H*.76};gestures(e=>{e.preventDefault();let p=pxy(e),lane=p.x<W/3?0:p.x<2*W/3?1:2;let best=-1,bd=999;state.notes.forEach((n,i)=>{if(n.lane===lane){let d=Math.abs(n.y-state.hitY);if(d<bd){bd=d;best=i}}});if(best>=0&&bd<48){state.notes.splice(best,1);state.score++;metric.textContent=state.score+' / 14';if(state.score>=14){clearGestures();return win('Quattordici a tempo. Questa era sospettosamente brava. ✨')}}else loseLife('Tre tocchi fuori tempo. Il beat non era personale.')},null,null)}
function updateRhythm(dt){state.time-=dt;state.spawn-=dt;if(state.time<=0){clearGestures();return lose('Canzone finita prima dei 14 colpi. Ancora una.')}if(state.spawn<=0){state.spawn=.48-Math.min(.14,state.score*.006);state.notes.push({lane:Math.floor(Math.random()*3),y:95,v:205+state.score*4,em:['💋','🌹','✨'][Math.floor(Math.random()*3)]})}for(let i=state.notes.length-1;i>=0;i--){let n=state.notes[i];n.y+=n.v*dt;if(n.y>state.hitY+62){state.notes.splice(i,1);if(loseLife('Ne hai lasciati passare tre. Il ritmo è vendicativo.'))return}}ctx.strokeStyle='#ffffff0d';ctx.lineWidth=1;for(let i=1;i<3;i++){ctx.beginPath();ctx.moveTo(W*i/3,100);ctx.lineTo(W*i/3,H-60);ctx.stroke()}ctx.strokeStyle='#ffb1ca88';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(18,state.hitY);ctx.lineTo(W-18,state.hitY);ctx.stroke();state.notes.forEach(n=>emoji(n.em,state.lanes[n.lane],n.y,36));['SIN','CENTRO','DES'].forEach((s,i)=>txt(s,state.lanes[i],state.hitY+42,9,'#8f818c'))}

/* 05 — TORRE DI ROSE */
function initStack(){setHUD('05 // TORRE DI ROSE','1 / 7');setLives(3);tip.textContent='Tocca per far cadere il blocco. Impilane 7 🌹';let base={x:W/2-62,y:H*.76,w:124,h:30};state={lives:3,count:1,blocks:[base],moving:{x:22,y:base.y-58,w:116,h:30,v:155,dir:1}};gestures(e=>{e.preventDefault();dropStack()},null,null)}
function dropStack(){let m=state.moving,top=state.blocks[state.blocks.length-1];let left=Math.max(m.x,top.x),right=Math.min(m.x+m.w,top.x+top.w),ov=right-left;if(ov<34){if(loseLife('La torre è caduta tre volte. Le rose chiedono più precisione.'))return;state.moving={x:22,y:top.y-58,w:Math.max(72,top.w),h:30,v:165+state.count*12,dir:1};return}let b={x:left,y:m.y,w:ov,h:30};state.blocks.push(b);state.count++;metric.textContent=state.count+' / 7';if(state.count>=7){clearGestures();return win('Sette piani di rose. Totalmente necessario. 🌹')}state.moving={x:W-mathSafeW(b.w)-22,y:b.y-58,w:b.w,h:30,v:165+state.count*13,dir:-1}}
function mathSafeW(w){return Math.max(48,w)}
function updateStack(dt){let m=state.moving;m.x+=m.v*m.dir*dt;if(m.x<12){m.x=12;m.dir=1}if(m.x+m.w>W-12){m.x=W-12-m.w;m.dir=-1}state.blocks.forEach((b,i)=>{rr(b.x,b.y,b.w,b.h,10);ctx.fillStyle=i===0?'#ffffff0d':'#ff78a725';ctx.fill();ctx.strokeStyle='#ffffff18';ctx.stroke();emoji('🌹',b.x+b.w/2,b.y+b.h/2,24)});rr(m.x,m.y,m.w,m.h,10);ctx.fillStyle='#ffb1ca35';ctx.fill();ctx.strokeStyle='#ffb1ca88';ctx.stroke();emoji('🌹',m.x+m.w/2,m.y+m.h/2,24)}
