/* LIVELLO 3 */
function initTiming(){setHUD("03 // TEMPISMO","0 / 5");setLives(3);joy.classList.remove("on");tip.textContent="Tocca quando la linea bianca entra nella zona rosa";state={hits:0,lives:3,pos:0,dir:1,speed:.88,target:.5,tw:.18,round:0,cool:0};setCanvasTap(()=>timingTap())}
function timingTap(){if(state.cool>0)return;let d=Math.abs(state.pos-state.target),ok=d<state.tw/2;state.cool=.30;if(ok){state.hits++;state.round++;metric.textContent=state.hits+" / 5";state.target=.16+Math.random()*.68;state.tw=Math.max(.075,.18-state.round*.019);state.speed+=.15;if(state.hits>=5)return win("Cinque centri. Bel dito.")}else{state.lives--;setLives(state.lives);flashBad();if(state.lives<=0)return lose("Tre tocchi fuori tempo. Ancora una.")}}
function updateTiming(dt){state.cool=Math.max(0,state.cool-dt);state.pos+=state.dir*state.speed*dt;if(state.pos>1){state.pos=1;state.dir=-1}else if(state.pos<0){state.pos=0;state.dir=1}const x=28,y=H*.49,w=W-56,h=34;rr(x,y,w,h,17);ctx.fillStyle="#ffffff0b";ctx.fill();let zx=x+(state.target-state.tw/2)*w,zw=state.tw*w;rr(zx,y+3,zw,h-6,14);ctx.fillStyle="#ff78a766";ctx.fill();let px=x+state.pos*w;ctx.fillStyle="#fff";rr(px-3,y-12,6,h+24,3);ctx.fill();emoji("💋",W/2,y-62,31)}
/* LIVELLO 4 */
function initMemory(){setHUD("04 // MEMORIA","1 / 7");setLives(3);tip.textContent="Guarda i lampi · poi ripetili nello stesso ordine";state={seq:[],input:[],round:1,lives:3,mode:"wait",showIndex:0,lit:false,timer:.25,flash:-1};state.seq=[randPad(),randPad(),randPad()];startMemoryShow(.3);setCanvasTap(p=>memoryTap(p))}
function randPad(){return Math.floor(Math.random()*4)}
function padRects(){const gap=10,size=Math.min((W-44-gap)/2,146),total=size*2+gap,x=(W-total)/2,y=H*.36;return[{x,y,w:size,h:size},{x:x+size+gap,y,w:size,h:size},{x,y:y+size+gap,w:size,h:size},{x:x+size+gap,y:y+size+gap,w:size,h:size}]}
function startMemoryShow(delay=.18){state.mode="delay";state.showIndex=0;state.lit=false;state.timer=delay;state.input=[];tip.textContent="Guarda bene 👀"}
function memoryTap(p){if(state.mode!=="input")return;const R=padRects();let k=R.findIndex(r=>p.x>=r.x&&p.x<=r.x+r.w&&p.y>=r.y&&p.y<=r.y+r.h);if(k<0)return;state.flash=k;setTimeout(()=>{if(state)state.flash=-1},105);let expected=state.seq[state.input.length];if(k!==expected){state.lives--;setLives(state.lives);flashBad();state.input=[];if(state.lives<=0)return lose("La sequenza ti ha fregata. Te la faccio rivedere.");startMemoryShow(.35);return}state.input.push(k);if(state.input.length===state.seq.length){if(state.round>=7)return win("Sette round fatti. Questa memoria funziona bene.");state.round++;metric.textContent=state.round+" / 7";state.seq.push(randPad());state.mode="wait";tip.textContent="bene ✨";setTimeout(()=>{if(active)startMemoryShow(.20)},260)}}
function updateMemory(dt){state.timer-=dt;if(state.mode==="delay"&&state.timer<=0){state.mode="show";state.lit=true;state.showIndex=0;state.timer=Math.max(.21,.34-state.round*.014)}else if(state.mode==="show"&&state.timer<=0){if(state.lit){state.lit=false;state.timer=.10}else{state.showIndex++;if(state.showIndex>=state.seq.length){state.mode="input";state.lit=false;tip.textContent="Adesso tocca a te 👆"}else{state.lit=true;state.timer=Math.max(.21,.34-state.round*.014)}}}const R=padRects(),cols=["#ff8eb4","#ffd58e","#ff6f8f","#c9b0ff"],labels=["💋","🌹","❤️","✨"],dx=[0,0,-4,0];R.forEach((r,i)=>{let on=(state.mode==="show"&&state.lit&&state.seq[state.showIndex]===i)||state.flash===i;rr(r.x,r.y,r.w,r.h,24);ctx.fillStyle=on?cols[i]+"66":"#ffffff09";ctx.fill();ctx.strokeStyle=on?"#ffffffaa":"#ffffff12";ctx.lineWidth=on?2:1.5;ctx.stroke();emoji(labels[i],r.x+r.w/2+dx[i],r.y+r.h/2,on?46:39)})}
/* LIVELLO 5 */
function initMaze(){setHUD("05 // LABIRINTO","❤️ → USCITA");setLives(3);joy.classList.add("on");tip.textContent="Porta ❤️ all'uscita · senza fretta";const walls=makeMaze();const spawn=findSafeMazeSpawn(walls);state={p:{x:spawn.x,y:spawn.y,r:9,hitR:7},lives:3,inv:0,walls,goal:{x:W/2-38,y:90,w:76,h:32}};setCanvasTap(()=>{})}
function gateWalls(y,c,gap=94,h=17){let out=[];let leftW=Math.max(0,c-gap/2);let rightX=c+gap/2;out.push({x:0,y,w:leftW,h,vx:0});out.push({x:rightX,y,w:Math.max(0,W-rightX),h,vx:0});return out}
function makeMaze(){let walls=[];[[H*.76,W*.27],[H*.63,W*.71],[H*.50,W*.34],[H*.37,W*.68],[H*.25,W*.48]].forEach(([y,c])=>walls.push(...gateWalls(y,c)));walls.push({x:W*.42,y:H*.565,w:68,h:15,vx:78,min:20,max:W-88});walls.push({x:W*.18,y:H*.31,w:64,h:15,vx:-70,min:20,max:W-84});return walls}
function collideCircleRect(p,r){const inset=2,hitR=p.hitR||p.r,x1=r.x+inset,x2=r.x+r.w-inset,y1=r.y+inset,y2=r.y+r.h-inset;let cx=Math.max(x1,Math.min(p.x,x2)),cy=Math.max(y1,Math.min(p.y,y2));return Math.hypot(p.x-cx,p.y-cy)<hitR}
function findSafeMazeSpawn(walls){const r=9,hitR=7,candidates=[{x:W/2,y:H-105},{x:W*.72,y:H-105},{x:W*.28,y:H-105},{x:W/2,y:H-135}];for(const c of candidates){let p={x:c.x,y:c.y,r,hitR};if(c.y>100&&c.y<H-65&&!walls.some(w=>collideCircleRect(p,w)))return c}for(let y=H-90;y>H*.79;y-=18){for(let x=30;x<W-30;x+=24){let p={x,y,r,hitR};if(!walls.some(w=>collideCircleRect(p,w)))return{x,y}}}return{x:W/2,y:H-80}}
function updateMaze(dt){metric.textContent="❤️ → USCITA";let p=state.p,old={x:p.x,y:p.y};p.x=Math.max(11,Math.min(W-11,p.x+j.dx*205*dt));p.y=Math.max(85,Math.min(H-65,p.y+j.dy*205*dt));state.inv=Math.max(0,state.inv-dt);state.walls.forEach(r=>{if(r.vx){r.x+=r.vx*dt;if(r.x<r.min||r.x>r.max){r.vx*=-1;r.x=Math.max(r.min,Math.min(r.max,r.x))}}});if(state.inv<=0&&state.walls.some(r=>collideCircleRect(p,r))){p.x=old.x;p.y=old.y;state.lives--;setLives(state.lives);state.inv=.48;flashBad();if(state.lives<=0)return lose("Tre tocchi ai muri. Il cuore merita un'altra possibilità.")}let g=state.goal;if(p.x>g.x&&p.x<g.x+g.w&&p.y<g.y+g.h)return win("Arrivato ❤️");rr(g.x,g.y,g.w,g.h,15);ctx.fillStyle="#a8ffcf22";ctx.fill();ctx.strokeStyle="#a8ffcf99";ctx.stroke();txt("USCITA",g.x+g.w/2,g.y+g.h/2,10,"#a8ffcf");state.walls.forEach(r=>{rr(r.x,r.y,r.w,r.h,8);ctx.fillStyle=r.vx?"#ffffff1b":"#ffffff11";ctx.fill();ctx.strokeStyle="#ffffff1c";ctx.stroke()});emoji("❤️",p.x,p.y,22)}
