/* LIVELLO 1 */
function initCatch(){setHUD("01 // BACINI","0 / 14");setLives(3);tip.textContent="Prendi 💋 e 🌹 · lascia stare 💔";state={score:0,lives:3,combo:0,targets:[],spawn:0,time:20};setCanvasTap(p=>{let hit=false;for(let i=state.targets.length-1;i>=0;i--){let a=state.targets[i];if(Math.hypot(p.x-a.x,p.y-a.y)<a.r+14){hit=true;state.targets.splice(i,1);if(a.bad){state.lives--;state.combo=0;setLives(state.lives);flashBad();if(state.lives<=0)return lose("Tre cuori rotti toccati. Direi che possiamo rifarla.")}else{state.combo++;state.score+=state.combo>=4?2:1;metric.textContent=state.score+" / 14";if(state.score>=14)return win("Presi. Bonus bacini moralmente approvato.")}break}}if(!hit){state.combo=0;state.lives--;setLives(state.lives);flashBad();if(state.lives<=0)lose("Tre tocchi nel vuoto. Succede.")}})}
function flashBad(){game.classList.remove("shake");void game.offsetWidth;game.classList.add("shake")}
function updateCatch(dt){state.time-=dt;state.spawn-=dt;if(state.time<=0)return lose("Tempo finito a "+state.score+" punti. Eri quasi lì.");if(state.spawn<=0){state.spawn=Math.max(.27,.54-(20-state.time)*.012);const roll=Math.random(),bad=roll<.22,sym=bad?"💔":roll<.66?"💋":"🌹",r=24+Math.random()*6;state.targets.push({x:36+Math.random()*(W-72),y:118+Math.random()*(H-250),r,bad,sym,life:.95+Math.random()*.42})}for(let i=state.targets.length-1;i>=0;i--){let a=state.targets[i];a.life-=dt;if(a.life<=0){state.targets.splice(i,1);if(!a.bad){state.combo=0;state.lives--;setLives(state.lives);if(state.lives<=0)return lose("Ne sono scappati tre. Riproviamo.")}}}state.targets.forEach(a=>{circle(a.x,a.y,a.r+8,"#ffffff0c");emoji(a.sym,a.x,a.y,a.r*1.55)});txt("SERIE ×"+state.combo,16,92,12,state.combo>=4?"#ffd58e":"#a99ba8","left",850)}
/* JOYSTICK */
let j={active:false,id:null,cx:0,cy:0,dx:0,dy:0};
function resetJoy(){j={active:false,id:null,cx:0,cy:0,dx:0,dy:0};stick.style.transform="translate(0,0)"}
joy.addEventListener("pointerdown",e=>{e.preventDefault();joy.setPointerCapture(e.pointerId);j.active=true;j.id=e.pointerId;const r=joy.getBoundingClientRect();j.cx=r.left+r.width/2;j.cy=r.top+r.height/2;moveJoy(e)},{passive:false});
joy.addEventListener("pointermove",e=>{if(j.active&&e.pointerId===j.id)moveJoy(e)},{passive:false});joy.addEventListener("pointerup",e=>{if(e.pointerId===j.id)resetJoy()});joy.addEventListener("pointercancel",resetJoy);
function moveJoy(e){let dx=e.clientX-j.cx,dy=e.clientY-j.cy,d=Math.hypot(dx,dy),m=33;if(d>m){dx*=m/d;dy*=m/d}j.dx=dx/m;j.dy=dy/m;stick.style.transform=`translate(${dx}px,${dy}px)`}
/* LIVELLO 2 */
function initDodge(){setHUD("02 // SCHIVA","18.0s");setLives(3);joy.classList.add("on");tip.textContent="Muovi Amelie col joystick a destra · evita i 💋";state={p:{x:W/2,y:H*.64,r:18},lives:3,time:18,spawn:.38,shots:[],inv:0};setCanvasTap(()=>{})}
function spawnEdgeShot(speed){let side=Math.floor(Math.random()*4),x,y;if(side===0){x=Math.random()*W;y=75}else if(side===1){x=W+20;y=105+Math.random()*(H-260)}else if(side===2){x=Math.random()*W;y=H+20}else{x=-20;y=105+Math.random()*(H-260)}let tx=state.p.x+(Math.random()-.5)*80,ty=state.p.y+(Math.random()-.5)*80,d=Math.hypot(tx-x,ty-y);state.shots.push({x,y,vx:(tx-x)/d*speed,vy:(ty-y)/d*speed,r:12})}
function updateDodge(dt){state.time-=dt;metric.textContent=Math.max(0,state.time).toFixed(1)+"s";if(state.time<=0)return win("18 secondi. Nessun bacino a segno. Impressionante.");let p=state.p,sp=235;p.x=Math.max(20,Math.min(W-20,p.x+j.dx*sp*dt));p.y=Math.max(118,Math.min(H-155,p.y+j.dy*sp*dt));state.inv=Math.max(0,state.inv-dt);state.spawn-=dt;if(state.spawn<=0){let elapsed=18-state.time;state.spawn=Math.max(.24,.59-elapsed*.019);spawnEdgeShot(125+elapsed*6.5)}for(let i=state.shots.length-1;i>=0;i--){let s=state.shots[i];s.x+=s.vx*dt;s.y+=s.vy*dt;if(s.x<-50||s.x>W+50||s.y<50||s.y>H+50){state.shots.splice(i,1);continue}if(state.inv<=0&&Math.hypot(s.x-p.x,s.y-p.y)<s.r+p.r-3){state.shots.splice(i,1);state.lives--;setLives(state.lives);state.inv=.78;flashBad();if(state.lives<=0)return lose("Tre bacini a segno. Musino festeggia, tu riprovi.")}}state.shots.forEach(s=>{circle(s.x,s.y,22,"#ff78a710");emoji("💋",s.x,s.y,30)});avatar(p.x,p.y,p.r,state.inv)}
