/* LEVEL 1 */
function initCatch(){setHUD("01 // CACCIA","0 / 14");setLives(3);tip.textContent="tocca ♥ e 🌹 · evita 💔";state={score:0,lives:3,combo:0,targets:[],spawn:0,time:22};setCanvasTap(p=>{let hit=false;for(let i=state.targets.length-1;i>=0;i--){let a=state.targets[i];if(Math.hypot(p.x-a.x,p.y-a.y)<a.r+12){hit=true;state.targets.splice(i,1);if(a.bad){state.lives--;state.combo=0;setLives(state.lives);flashBad();if(state.lives<=0)return lose("Hai toccato troppi cuori rotti. Metaforicamente sospetto.")}else{state.combo++;state.score+=state.combo>=4?2:1;metric.textContent=state.score+" / 14";if(state.score>=14)return win("Combo completata. Le dita funzionano.")}break}}if(!hit){state.combo=0;state.lives--;setLives(state.lives);flashBad();if(state.lives<=0)lose("Tre tocchi nel nulla. Precisione creativa.")}})}
function flashBad(){game.classList.remove("shake");void game.offsetWidth;game.classList.add("shake")}
function updateCatch(dt){state.time-=dt;state.spawn-=dt;if(state.time<=0)return lose("Tempo scaduto a "+state.score+" punti. Il cronometro non prova empatia.");if(state.spawn<=0){state.spawn=Math.max(.34,.66-(22-state.time)*.012);const bad=Math.random()<.23,r=22+Math.random()*8;state.targets.push({x:35+Math.random()*(W-70),y:110+Math.random()*(H-220),r,bad,life:1.15+Math.random()*.5})}for(let i=state.targets.length-1;i>=0;i--){let a=state.targets[i];a.life-=dt;if(a.life<=0){state.targets.splice(i,1);if(!a.bad){state.combo=0;state.lives--;setLives(state.lives);if(state.lives<=0)return lose("Ne hai lasciati scappare tre. I bacini non aspettano.")}}}state.targets.forEach(a=>{circle(a.x,a.y,a.r+7,"#ffffff0c");heart(a.x,a.y,a.r,a.bad?"#786675":"#ff78a7");if(a.bad)txt("×",a.x,a.y-1,18,"#fff","center",900)});txt("COMBO ×"+state.combo,16,82,12,state.combo>=4?"#ffd58e":"#a99ba8","left",850)}
/* JOYSTICK */
let j={active:false,id:null,cx:0,cy:0,dx:0,dy:0};
function resetJoy(){j={active:false,id:null,cx:0,cy:0,dx:0,dy:0};stick.style.transform="translate(0,0)"}
joy.addEventListener("pointerdown",e=>{e.preventDefault();joy.setPointerCapture(e.pointerId);j.active=true;j.id=e.pointerId;const r=joy.getBoundingClientRect();j.cx=r.left+r.width/2;j.cy=r.top+r.height/2;moveJoy(e)},{passive:false});
joy.addEventListener("pointermove",e=>{if(j.active&&e.pointerId===j.id)moveJoy(e)},{passive:false});joy.addEventListener("pointerup",e=>{if(e.pointerId===j.id)resetJoy()});joy.addEventListener("pointercancel",resetJoy);
function moveJoy(e){let dx=e.clientX-j.cx,dy=e.clientY-j.cy,d=Math.hypot(dx,dy),m=33;if(d>m){dx*=m/d;dy*=m/d}j.dx=dx/m;j.dy=dy/m;stick.style.transform=`translate(${dx}px,${dy}px)`}
/* LEVEL 2 */
function initDodge(){setHUD("02 // SCHIVA","18.0s");setLives(3);joy.classList.add("on");tip.textContent="joystick a destra · resisti 18 secondi";state={p:{x:W/2,y:H*.68,r:15},lives:3,time:18,spawn:.4,shots:[],inv:0};setCanvasTap(()=>{})}
function spawnEdgeShot(speed){let side=Math.floor(Math.random()*4),x,y;if(side===0){x=Math.random()*W;y=65}else if(side===1){x=W+15;y=80+Math.random()*(H-150)}else if(side===2){x=Math.random()*W;y=H+15}else{x=-15;y=80+Math.random()*(H-150)}let tx=state.p.x+(Math.random()-.5)*70,ty=state.p.y+(Math.random()-.5)*70,d=Math.hypot(tx-x,ty-y);state.shots.push({x,y,vx:(tx-x)/d*speed,vy:(ty-y)/d*speed,r:10})}
function updateDodge(dt){state.time-=dt;metric.textContent=Math.max(0,state.time).toFixed(1)+"s";if(state.time<=0)return win("18 secondi. Il bacino non ti ha presa. Per ora.");let p=state.p,sp=230;p.x=Math.max(18,Math.min(W-18,p.x+j.dx*sp*dt));p.y=Math.max(78,Math.min(H-22,p.y+j.dy*sp*dt));state.inv=Math.max(0,state.inv-dt);state.spawn-=dt;if(state.spawn<=0){let elapsed=18-state.time;state.spawn=Math.max(.22,.62-elapsed*.02);spawnEdgeShot(125+elapsed*7)}for(let i=state.shots.length-1;i>=0;i--){let s=state.shots[i];s.x+=s.vx*dt;s.y+=s.vy*dt;if(s.x<-40||s.x>W+40||s.y<30||s.y>H+40){state.shots.splice(i,1);continue}if(state.inv<=0&&Math.hypot(s.x-p.x,s.y-p.y)<s.r+p.r){state.shots.splice(i,1);state.lives--;setLives(state.lives);state.inv=.75;flashBad();if(state.lives<=0)return lose("Il bacino ha vinto. Tre volte, per essere precisi.")}}state.shots.forEach(s=>{heart(s.x,s.y,13,"#ff8eb4");circle(s.x,s.y,3,"#fff5")});circle(p.x,p.y,p.r+5,state.inv>0?"#ffffff22":"#ffb1ca22");circle(p.x,p.y,p.r,"#f6e7ef");txt("A",p.x,p.y+1,12,"#3c1b29")}
