/* LEVEL 3 */
function initTiming(){setHUD("03 // TEMPISMO","0 / 5");setLives(3);joy.classList.remove("on");tip.textContent="tocca quando l'indicatore entra nella zona rosa";state={hits:0,lives:3,pos:0,dir:1,speed:.78,target:.5,tw:.18,round:0,cool:0};setCanvasTap(()=>timingTap())}
function timingTap(){if(state.cool>0)return;let d=Math.abs(state.pos-state.target),ok=d<state.tw/2;state.cool=.42;if(ok){state.hits++;state.round++;metric.textContent=state.hits+" / 5";state.target=.18+Math.random()*.64;state.tw=Math.max(.08,.18-state.round*.018);state.speed+=.13;if(state.hits>=5)return win("Cinque centri. Sorprendentemente precisa.")}else{state.lives--;setLives(state.lives);flashBad();if(state.lives<=0)return lose("Tre errori di tempismo. Il bacino richiede coordinazione.")}}
function updateTiming(dt){state.cool=Math.max(0,state.cool-dt);state.pos+=state.dir*state.speed*dt;if(state.pos>1){state.pos=1;state.dir=-1}else if(state.pos<0){state.pos=0;state.dir=1}const x=30,y=H*.48,w=W-60,h=32;rr(x,y,w,h,16);ctx.fillStyle="#ffffff0b";ctx.fill();let zx=x+(state.target-state.tw/2)*w,zw=state.tw*w;rr(zx,y+3,zw,h-6,14);ctx.fillStyle="#ff78a755";ctx.fill();let px=x+state.pos*w;ctx.fillStyle="#fff";rr(px-3,y-11,6,h+22,3);ctx.fill();txt("ORA",W/2,y-50,13,"#b9adb8")}
/* LEVEL 4 */
function initMemory(){setHUD("04 // MEMORIA","round 1 / 7");setLives(3);tip.textContent="guarda bene · poi ripeti nello stesso ordine";state={pads:[0,1,2,3],seq:[],input:[],round:1,lives:3,mode:"show",showIndex:-1,timer:.55,flash:-1};addMemoryItem();addMemoryItem();setCanvasTap(p=>memoryTap(p))}
function padRects(){const gap=10,size=Math.min((W-44-gap)/2,146),total=size*2+gap,x=(W-total)/2,y=H*.37;return[{x,y,w:size,h:size},{x:x+size+gap,y,w:size,h:size},{x,y:y+size+gap,w:size,h:size},{x:x+size+gap,y:y+size+gap,w:size,h:size}]}
function addMemoryItem(){state.seq.push(Math.floor(Math.random()*4));state.mode="show";state.showIndex=-1;state.timer=.55;state.input=[];tip.textContent="guarda bene"}
function memoryTap(p){if(state.mode!=="input")return;const R=padRects();let k=R.findIndex(r=>p.x>=r.x&&p.x<=r.x+r.w&&p.y>=r.y&&p.y<=r.y+r.h);if(k<0)return;state.flash=k;setTimeout(()=>{if(state)state.flash=-1},120);let expected=state.seq[state.input.length];if(k!==expected){state.lives--;setLives(state.lives);flashBad();state.input=[];if(state.lives<=0)return lose("La sequenza era appena comparsa. Questa farà male all'orgoglio.");state.mode="show";state.showIndex=-1;state.timer=.55;tip.textContent="te la faccio rivedere. Una volta.";return}state.input.push(k);if(state.input.length===state.seq.length){if(state.round>=7)return win("Sette sequenze. Memoria ufficialmente approvata.");state.round++;metric.textContent="round "+state.round+" / 7";setTimeout(()=>{if(active){addMemoryItem();if(state.round>=5&&Math.random()<.55)addMemoryItem()}},330);state.mode="wait"}}
function updateMemory(dt){if(state.mode==="show"){state.timer-=dt;if(state.timer<=0){state.showIndex++;if(state.showIndex>=state.seq.length){state.mode="input";state.showIndex=-1;tip.textContent="adesso tocca a te"}else{state.timer=Math.max(.28,.5-state.round*.035)}}}const R=padRects(),cols=["#ff88ae","#ffd58e","#a8c8ff","#c7a8ff"],labels=["♥","✦","●","◆"];R.forEach((r,i)=>{let lit=(state.mode==="show"&&state.showIndex>=0&&state.seq[state.showIndex]===i)||state.flash===i;rr(r.x,r.y,r.w,r.h,24);ctx.fillStyle=lit?cols[i]:"#ffffff09";ctx.fill();ctx.strokeStyle=lit?"#ffffff90":"#ffffff12";ctx.lineWidth=1.5;ctx.stroke();txt(labels[i],r.x+r.w/2,r.y+r.h/2,34,lit?"#21131d":"#7d727d")})}
/* LEVEL 5 */
function initMaze(){setHUD("05 // LABIRINTO","20.0s");setLives(3);joy.classList.add("on");tip.textContent="joystick a destra · porta il cuore all'uscita in alto";const walls=makeMaze();state={p:{x:W/2,y:H-118,r:12},lives:3,time:20,inv:0,walls,goal:{x:W/2-34,y:72,w:68,h:30}};setCanvasTap(()=>{})}
function makeMaze(){const p=16;return[
{x:p,y:H*.77,w:W*.70,h:18,vx:0},
{x:W*.34,y:H*.66,w:W*.66-p,h:18,vx:0},
{x:p,y:H*.55,w:W*.58,h:18,vx:0},
{x:W*.43,y:H*.44,w:W*.57-p,h:18,vx:0},
{x:p,y:H*.33,w:W*.60,h:18,vx:0},
{x:W*.32,y:H*.23,w:W*.54,h:18,vx:72},
{x:W*.08,y:H*.48,w:W*.34,h:16,vx:-88},
{x:W*.46,y:H*.60,w:W*.30,h:16,vx:94},
{x:W*.18,y:H*.15,w:W*.31,h:16,vx:-76}
]}
function collideCircleRect(p,r){let cx=Math.max(r.x,Math.min(p.x,r.x+r.w)),cy=Math.max(r.y,Math.min(p.y,r.y+r.h));return Math.hypot(p.x-cx,p.y-cy)<p.r}
function updateMaze(dt){state.time-=dt;metric.textContent=Math.max(0,state.time).toFixed(1)+"s";if(state.time<=0)return lose("Tempo finito. Il labirinto ha avuto l'ultima parola.");let p=state.p,old={x:p.x,y:p.y};p.x=Math.max(14,Math.min(W-14,p.x+j.dx*190*dt));p.y=Math.max(70,Math.min(H-16,p.y+j.dy*190*dt));state.inv=Math.max(0,state.inv-dt);state.walls.forEach((r,i)=>{if(r.vx){r.x+=r.vx*dt;if(r.x<10||r.x+r.w>W-10){r.vx*=-1;r.x=Math.max(10,Math.min(W-10-r.w,r.x))}}});if(state.inv<=0&&state.walls.some(r=>collideCircleRect(p,r))){p.x=old.x;p.y=old.y;state.lives--;setLives(state.lives);state.inv=.5;flashBad();if(state.lives<=0)return lose("Tre collisioni. Forse il muro era abbastanza visibile.")}let g=state.goal;if(p.x>g.x&&p.x<g.x+g.w&&p.y<g.y+g.h)return win("Uscita raggiunta. Il cuore è arrivato con qualche trauma, ma è arrivato.");rr(g.x,g.y,g.w,g.h,15);ctx.fillStyle="#a8ffcf22";ctx.fill();ctx.strokeStyle="#a8ffcf88";ctx.stroke();txt("USCITA",g.x+g.w/2,g.y+g.h/2,10,"#a8ffcf");state.walls.forEach(r=>{rr(r.x,r.y,r.w,r.h,8);ctx.fillStyle=r.vx?"#ffffff19":"#ffffff11";ctx.fill();ctx.strokeStyle="#ffffff1c";ctx.stroke()});emoji("❤️",p.x,p.y,27)}
